-- Phase 1: Create drills and drill_categories tables, update completed_drills, add constraints

-- 1.1 Create drills table
CREATE TABLE IF NOT EXISTS public.drills (
  id text PRIMARY KEY,
  sport text NOT NULL,
  category text NOT NULL,
  category_name text,
  level int NOT NULL,
  title text NOT NULL,
  description text,
  duration_minutes int NOT NULL DEFAULT 7,
  solo_or_duo text DEFAULT 'solo',
  equipment jsonb DEFAULT '[]'::jsonb,
  steps jsonb DEFAULT '[]'::jsonb,
  metric jsonb DEFAULT '{}'::jsonb,
  xp int NOT NULL DEFAULT 30,
  free boolean DEFAULT false,
  unlock_requires text DEFAULT 'none',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 1.2 Create drill_categories table
CREATE TABLE IF NOT EXISTS public.drill_categories (
  id text PRIMARY KEY,
  sport text NOT NULL,
  name text NOT NULL,
  levels int NOT NULL DEFAULT 10,
  drills_per_level int NOT NULL DEFAULT 3,
  created_at timestamptz DEFAULT now()
);

-- 1.3 Add score_data column to completed_drills if not exists
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'completed_drills' AND column_name = 'score_data') THEN
    ALTER TABLE public.completed_drills ADD COLUMN score_data jsonb DEFAULT NULL;
  END IF;
END $$;

-- 1.4 Add unique constraint to daily_progress if not exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_progress_user_date_unique') THEN
    ALTER TABLE public.daily_progress ADD CONSTRAINT daily_progress_user_date_unique UNIQUE (user_id, date);
  END IF;
END $$;

-- 1.5 Enable RLS on drills and drill_categories
ALTER TABLE public.drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drill_categories ENABLE ROW LEVEL SECURITY;

-- 1.5.1 RLS Policies for drills - public read access
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'drills' AND policyname = 'Drills are viewable by everyone') THEN
    CREATE POLICY "Drills are viewable by everyone" ON public.drills FOR SELECT USING (true);
  END IF;
END $$;

-- 1.5.2 RLS Policies for drill_categories - public read access
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'drill_categories' AND policyname = 'Categories are viewable by everyone') THEN
    CREATE POLICY "Categories are viewable by everyone" ON public.drill_categories FOR SELECT USING (true);
  END IF;
END $$;

-- 1.6 Insert drill categories (idempotent)
INSERT INTO public.drill_categories (id, sport, name, levels, drills_per_level) VALUES
  ('dribbling', 'football', 'Dribbling', 10, 3),
  ('passing', 'football', 'Passing', 10, 3),
  ('shooting', 'football', 'Shooting', 10, 3),
  ('control', 'football', 'Ball Control', 10, 3),
  ('fitness', 'football', 'Fitness & Agility', 10, 3)
ON CONFLICT (id) DO UPDATE SET
  sport = EXCLUDED.sport,
  name = EXCLUDED.name,
  levels = EXCLUDED.levels,
  drills_per_level = EXCLUDED.drills_per_level;

-- 1.7 Insert all 150 football drills (idempotent upserts)
-- Dribbling L1
INSERT INTO public.drills (id, sport, category, category_name, level, title, description, duration_minutes, solo_or_duo, equipment, steps, metric, xp, free, unlock_requires) VALUES
  ('football-dribbling-L01-001', 'football', 'dribbling', 'Dribbling', 1, 'Dribbling L1 Drill 1', 'Dribbling practice at level 1.', 7, 'solo', '["ball", "cones"]', '["Set 3 cones 1.2m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-dribbling-L01-002', 'football', 'dribbling', 'Dribbling', 1, 'Dribbling L1 Drill 2', 'Dribbling practice at level 1.', 7, 'duo', '["ball", "cones"]', '["Set 3 cones 1.2m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-dribbling-L01-003', 'football', 'dribbling', 'Dribbling', 1, 'Dribbling L1 Drill 3', 'Dribbling practice at level 1.', 7, 'solo', '["ball", "cones"]', '["Set 3 cones 1.2m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 24, true, 'none'),
  -- Dribbling L2
  ('football-dribbling-L02-001', 'football', 'dribbling', 'Dribbling', 2, 'Dribbling L2 Drill 1', 'Dribbling practice at level 2.', 9, 'solo', '["ball", "cones"]', '["Set 3 cones 1.4m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-dribbling-L02-002', 'football', 'dribbling', 'Dribbling', 2, 'Dribbling L2 Drill 2', 'Dribbling practice at level 2.', 9, 'duo', '["ball", "cones"]', '["Set 3 cones 1.4m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-dribbling-L02-003', 'football', 'dribbling', 'Dribbling', 2, 'Dribbling L2 Drill 3', 'Dribbling practice at level 2.', 9, 'solo', '["ball", "cones"]', '["Set 3 cones 1.4m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  -- Dribbling L3
  ('football-dribbling-L03-001', 'football', 'dribbling', 'Dribbling', 3, 'Dribbling L3 Drill 1', 'Dribbling practice at level 3.', 11, 'solo', '["ball", "cones"]', '["Set 3 cones 1.6m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-dribbling-L03-002', 'football', 'dribbling', 'Dribbling', 3, 'Dribbling L3 Drill 2', 'Dribbling practice at level 3.', 11, 'duo', '["ball", "cones"]', '["Set 3 cones 1.6m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-dribbling-L03-003', 'football', 'dribbling', 'Dribbling', 3, 'Dribbling L3 Drill 3', 'Dribbling practice at level 3.', 11, 'solo', '["ball", "cones"]', '["Set 3 cones 1.6m apart. Dribble through and back for 3 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  -- Dribbling L4
  ('football-dribbling-L04-001', 'football', 'dribbling', 'Dribbling', 4, 'Dribbling L4 Drill 1', 'Dribbling practice at level 4.', 13, 'solo', '["ball", "cones"]', '["Set 3 cones 1.8m apart. Dribble through and back for 4 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-dribbling-L04-002', 'football', 'dribbling', 'Dribbling', 4, 'Dribbling L4 Drill 2', 'Dribbling practice at level 4.', 13, 'duo', '["ball", "cones"]', '["Set 3 cones 1.8m apart. Dribble through and back for 4 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-dribbling-L04-003', 'football', 'dribbling', 'Dribbling', 4, 'Dribbling L4 Drill 3', 'Dribbling practice at level 4.', 13, 'solo', '["ball", "cones"]', '["Set 3 cones 1.8m apart. Dribble through and back for 4 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  -- Dribbling L5
  ('football-dribbling-L05-001', 'football', 'dribbling', 'Dribbling', 5, 'Dribbling L5 Drill 1', 'Dribbling practice at level 5.', 15, 'solo', '["ball", "cones"]', '["Set 3 cones 2.0m apart. Dribble through and back for 5 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-dribbling-L05-002', 'football', 'dribbling', 'Dribbling', 5, 'Dribbling L5 Drill 2', 'Dribbling practice at level 5.', 15, 'duo', '["ball", "cones"]', '["Set 3 cones 2.0m apart. Dribble through and back for 5 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-dribbling-L05-003', 'football', 'dribbling', 'Dribbling', 5, 'Dribbling L5 Drill 3', 'Dribbling practice at level 5.', 15, 'solo', '["ball", "cones"]', '["Set 3 cones 2.0m apart. Dribble through and back for 5 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  -- Dribbling L6
  ('football-dribbling-L06-001', 'football', 'dribbling', 'Dribbling', 6, 'Dribbling L6 Drill 1', 'Dribbling practice at level 6.', 17, 'solo', '["ball", "cones"]', '["Set 3 cones 2.2m apart. Dribble through and back for 6 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-dribbling-L06-002', 'football', 'dribbling', 'Dribbling', 6, 'Dribbling L6 Drill 2', 'Dribbling practice at level 6.', 17, 'duo', '["ball", "cones"]', '["Set 3 cones 2.2m apart. Dribble through and back for 6 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-dribbling-L06-003', 'football', 'dribbling', 'Dribbling', 6, 'Dribbling L6 Drill 3', 'Dribbling practice at level 6.', 17, 'solo', '["ball", "cones"]', '["Set 3 cones 2.2m apart. Dribble through and back for 6 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  -- Dribbling L7
  ('football-dribbling-L07-001', 'football', 'dribbling', 'Dribbling', 7, 'Dribbling L7 Drill 1', 'Dribbling practice at level 7.', 19, 'solo', '["ball", "cones"]', '["Set 3 cones 2.4m apart. Dribble through and back for 7 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-dribbling-L07-002', 'football', 'dribbling', 'Dribbling', 7, 'Dribbling L7 Drill 2', 'Dribbling practice at level 7.', 19, 'duo', '["ball", "cones"]', '["Set 3 cones 2.4m apart. Dribble through and back for 7 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-dribbling-L07-003', 'football', 'dribbling', 'Dribbling', 7, 'Dribbling L7 Drill 3', 'Dribbling practice at level 7.', 19, 'solo', '["ball", "cones"]', '["Set 3 cones 2.4m apart. Dribble through and back for 7 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  -- Dribbling L8
  ('football-dribbling-L08-001', 'football', 'dribbling', 'Dribbling', 8, 'Dribbling L8 Drill 1', 'Dribbling practice at level 8.', 21, 'solo', '["ball", "cones"]', '["Set 3 cones 2.6m apart. Dribble through and back for 8 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-dribbling-L08-002', 'football', 'dribbling', 'Dribbling', 8, 'Dribbling L8 Drill 2', 'Dribbling practice at level 8.', 21, 'duo', '["ball", "cones"]', '["Set 3 cones 2.6m apart. Dribble through and back for 8 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-dribbling-L08-003', 'football', 'dribbling', 'Dribbling', 8, 'Dribbling L8 Drill 3', 'Dribbling practice at level 8.', 21, 'solo', '["ball", "cones"]', '["Set 3 cones 2.6m apart. Dribble through and back for 8 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  -- Dribbling L9
  ('football-dribbling-L09-001', 'football', 'dribbling', 'Dribbling', 9, 'Dribbling L9 Drill 1', 'Dribbling practice at level 9.', 23, 'solo', '["ball", "cones"]', '["Set 3 cones 2.8m apart. Dribble through and back for 9 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-dribbling-L09-002', 'football', 'dribbling', 'Dribbling', 9, 'Dribbling L9 Drill 2', 'Dribbling practice at level 9.', 23, 'duo', '["ball", "cones"]', '["Set 3 cones 2.8m apart. Dribble through and back for 9 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-dribbling-L09-003', 'football', 'dribbling', 'Dribbling', 9, 'Dribbling L9 Drill 3', 'Dribbling practice at level 9.', 23, 'solo', '["ball", "cones"]', '["Set 3 cones 2.8m apart. Dribble through and back for 9 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  -- Dribbling L10
  ('football-dribbling-L10-001', 'football', 'dribbling', 'Dribbling', 10, 'Dribbling L10 Drill 1', 'Dribbling practice at level 10.', 25, 'solo', '["ball", "cones"]', '["Set 3 cones 3.0m apart. Dribble through and back for 10 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-dribbling-L10-002', 'football', 'dribbling', 'Dribbling', 10, 'Dribbling L10 Drill 2', 'Dribbling practice at level 10.', 25, 'duo', '["ball", "cones"]', '["Set 3 cones 3.0m apart. Dribble through and back for 10 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-dribbling-L10-003', 'football', 'dribbling', 'Dribbling', 10, 'Dribbling L10 Drill 3', 'Dribbling practice at level 10.', 25, 'solo', '["ball", "cones"]', '["Set 3 cones 3.0m apart. Dribble through and back for 10 reps.", "Focus on close touches and change of pace."]', '{"type": "mistakes", "target": "<=2 mistakes per rep", "success_eval": "self_or_partner_count", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  -- Passing L1
  ('football-passing-L01-001', 'football', 'passing', 'Passing', 1, 'Passing L1 Drill 1', 'Passing practice at level 1.', 7, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 6 passes from 4m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-passing-L01-002', 'football', 'passing', 'Passing', 1, 'Passing L1 Drill 2', 'Passing practice at level 1.', 7, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 6 passes from 4m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-passing-L01-003', 'football', 'passing', 'Passing', 1, 'Passing L1 Drill 3', 'Passing practice at level 1.', 7, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 6 passes from 4m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 24, true, 'none'),
  -- Passing L2-L10
  ('football-passing-L02-001', 'football', 'passing', 'Passing', 2, 'Passing L2 Drill 1', 'Passing practice at level 2.', 9, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 7 passes from 5m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-passing-L02-002', 'football', 'passing', 'Passing', 2, 'Passing L2 Drill 2', 'Passing practice at level 2.', 9, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 7 passes from 5m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-passing-L02-003', 'football', 'passing', 'Passing', 2, 'Passing L2 Drill 3', 'Passing practice at level 2.', 9, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 7 passes from 5m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-passing-L03-001', 'football', 'passing', 'Passing', 3, 'Passing L3 Drill 1', 'Passing practice at level 3.', 11, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 8 passes from 6m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-passing-L03-002', 'football', 'passing', 'Passing', 3, 'Passing L3 Drill 2', 'Passing practice at level 3.', 11, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 8 passes from 6m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-passing-L03-003', 'football', 'passing', 'Passing', 3, 'Passing L3 Drill 3', 'Passing practice at level 3.', 11, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 8 passes from 6m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-passing-L04-001', 'football', 'passing', 'Passing', 4, 'Passing L4 Drill 1', 'Passing practice at level 4.', 13, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 9 passes from 7m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-passing-L04-002', 'football', 'passing', 'Passing', 4, 'Passing L4 Drill 2', 'Passing practice at level 4.', 13, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 9 passes from 7m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-passing-L04-003', 'football', 'passing', 'Passing', 4, 'Passing L4 Drill 3', 'Passing practice at level 4.', 13, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 9 passes from 7m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-passing-L05-001', 'football', 'passing', 'Passing', 5, 'Passing L5 Drill 1', 'Passing practice at level 5.', 15, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 10 passes from 8m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-passing-L05-002', 'football', 'passing', 'Passing', 5, 'Passing L5 Drill 2', 'Passing practice at level 5.', 15, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 10 passes from 8m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-passing-L05-003', 'football', 'passing', 'Passing', 5, 'Passing L5 Drill 3', 'Passing practice at level 5.', 15, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 10 passes from 8m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-passing-L06-001', 'football', 'passing', 'Passing', 6, 'Passing L6 Drill 1', 'Passing practice at level 6.', 17, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 11 passes from 9m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-passing-L06-002', 'football', 'passing', 'Passing', 6, 'Passing L6 Drill 2', 'Passing practice at level 6.', 17, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 11 passes from 9m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-passing-L06-003', 'football', 'passing', 'Passing', 6, 'Passing L6 Drill 3', 'Passing practice at level 6.', 17, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 11 passes from 9m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-passing-L07-001', 'football', 'passing', 'Passing', 7, 'Passing L7 Drill 1', 'Passing practice at level 7.', 19, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 12 passes from 10m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-passing-L07-002', 'football', 'passing', 'Passing', 7, 'Passing L7 Drill 2', 'Passing practice at level 7.', 19, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 12 passes from 10m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-passing-L07-003', 'football', 'passing', 'Passing', 7, 'Passing L7 Drill 3', 'Passing practice at level 7.', 19, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 12 passes from 10m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-passing-L08-001', 'football', 'passing', 'Passing', 8, 'Passing L8 Drill 1', 'Passing practice at level 8.', 21, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 13 passes from 11m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-passing-L08-002', 'football', 'passing', 'Passing', 8, 'Passing L8 Drill 2', 'Passing practice at level 8.', 21, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 13 passes from 11m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-passing-L08-003', 'football', 'passing', 'Passing', 8, 'Passing L8 Drill 3', 'Passing practice at level 8.', 21, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 13 passes from 11m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-passing-L09-001', 'football', 'passing', 'Passing', 9, 'Passing L9 Drill 1', 'Passing practice at level 9.', 23, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 14 passes from 12m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-passing-L09-002', 'football', 'passing', 'Passing', 9, 'Passing L9 Drill 2', 'Passing practice at level 9.', 23, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 14 passes from 12m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-passing-L09-003', 'football', 'passing', 'Passing', 9, 'Passing L9 Drill 3', 'Passing practice at level 9.', 23, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 14 passes from 12m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-passing-L10-001', 'football', 'passing', 'Passing', 10, 'Passing L10 Drill 1', 'Passing practice at level 10.', 25, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 15 passes from 13m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-passing-L10-002', 'football', 'passing', 'Passing', 10, 'Passing L10 Drill 2', 'Passing practice at level 10.', 25, 'duo', '["ball"]', '["Partner up or use a wall. Complete sets of 15 passes from 13m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-passing-L10-003', 'football', 'passing', 'Passing', 10, 'Passing L10 Drill 3', 'Passing practice at level 10.', 25, 'solo', '["ball"]', '["Partner up or use a wall. Complete sets of 15 passes from 13m.", "Use both feet and follow through."]', '{"type": "accuracy", "target": ">=80% on target", "success_eval": "partner_count", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  -- Shooting L1-L10
  ('football-shooting-L01-001', 'football', 'shooting', 'Shooting', 1, 'Shooting L1 Drill 1', 'Shooting practice at level 1.', 7, 'solo', '["ball"]', '["Take 9 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level (e.g., 3/10 to 8/10)", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-shooting-L01-002', 'football', 'shooting', 'Shooting', 1, 'Shooting L1 Drill 2', 'Shooting practice at level 1.', 7, 'duo', '["ball"]', '["Take 9 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level (e.g., 3/10 to 8/10)", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-shooting-L01-003', 'football', 'shooting', 'Shooting', 1, 'Shooting L1 Drill 3', 'Shooting practice at level 1.', 7, 'solo', '["ball"]', '["Take 9 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level (e.g., 3/10 to 8/10)", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-shooting-L02-001', 'football', 'shooting', 'Shooting', 2, 'Shooting L2 Drill 1', 'Shooting practice at level 2.', 9, 'solo', '["ball"]', '["Take 10 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-shooting-L02-002', 'football', 'shooting', 'Shooting', 2, 'Shooting L2 Drill 2', 'Shooting practice at level 2.', 9, 'duo', '["ball"]', '["Take 10 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-shooting-L02-003', 'football', 'shooting', 'Shooting', 2, 'Shooting L2 Drill 3', 'Shooting practice at level 2.', 9, 'solo', '["ball"]', '["Take 10 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-shooting-L03-001', 'football', 'shooting', 'Shooting', 3, 'Shooting L3 Drill 1', 'Shooting practice at level 3.', 11, 'solo', '["ball"]', '["Take 11 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-shooting-L03-002', 'football', 'shooting', 'Shooting', 3, 'Shooting L3 Drill 2', 'Shooting practice at level 3.', 11, 'duo', '["ball"]', '["Take 11 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-shooting-L03-003', 'football', 'shooting', 'Shooting', 3, 'Shooting L3 Drill 3', 'Shooting practice at level 3.', 11, 'solo', '["ball"]', '["Take 11 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-shooting-L04-001', 'football', 'shooting', 'Shooting', 4, 'Shooting L4 Drill 1', 'Shooting practice at level 4.', 13, 'solo', '["ball"]', '["Take 12 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-shooting-L04-002', 'football', 'shooting', 'Shooting', 4, 'Shooting L4 Drill 2', 'Shooting practice at level 4.', 13, 'duo', '["ball"]', '["Take 12 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-shooting-L04-003', 'football', 'shooting', 'Shooting', 4, 'Shooting L4 Drill 3', 'Shooting practice at level 4.', 13, 'solo', '["ball"]', '["Take 12 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-shooting-L05-001', 'football', 'shooting', 'Shooting', 5, 'Shooting L5 Drill 1', 'Shooting practice at level 5.', 15, 'solo', '["ball"]', '["Take 13 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-shooting-L05-002', 'football', 'shooting', 'Shooting', 5, 'Shooting L5 Drill 2', 'Shooting practice at level 5.', 15, 'duo', '["ball"]', '["Take 13 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-shooting-L05-003', 'football', 'shooting', 'Shooting', 5, 'Shooting L5 Drill 3', 'Shooting practice at level 5.', 15, 'solo', '["ball"]', '["Take 13 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-shooting-L06-001', 'football', 'shooting', 'Shooting', 6, 'Shooting L6 Drill 1', 'Shooting practice at level 6.', 17, 'solo', '["ball"]', '["Take 14 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-shooting-L06-002', 'football', 'shooting', 'Shooting', 6, 'Shooting L6 Drill 2', 'Shooting practice at level 6.', 17, 'duo', '["ball"]', '["Take 14 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-shooting-L06-003', 'football', 'shooting', 'Shooting', 6, 'Shooting L6 Drill 3', 'Shooting practice at level 6.', 17, 'solo', '["ball"]', '["Take 14 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-shooting-L07-001', 'football', 'shooting', 'Shooting', 7, 'Shooting L7 Drill 1', 'Shooting practice at level 7.', 19, 'solo', '["ball"]', '["Take 15 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-shooting-L07-002', 'football', 'shooting', 'Shooting', 7, 'Shooting L7 Drill 2', 'Shooting practice at level 7.', 19, 'duo', '["ball"]', '["Take 15 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-shooting-L07-003', 'football', 'shooting', 'Shooting', 7, 'Shooting L7 Drill 3', 'Shooting practice at level 7.', 19, 'solo', '["ball"]', '["Take 15 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-shooting-L08-001', 'football', 'shooting', 'Shooting', 8, 'Shooting L8 Drill 1', 'Shooting practice at level 8.', 21, 'solo', '["ball"]', '["Take 16 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-shooting-L08-002', 'football', 'shooting', 'Shooting', 8, 'Shooting L8 Drill 2', 'Shooting practice at level 8.', 21, 'duo', '["ball"]', '["Take 16 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-shooting-L08-003', 'football', 'shooting', 'Shooting', 8, 'Shooting L8 Drill 3', 'Shooting practice at level 8.', 21, 'solo', '["ball"]', '["Take 16 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-shooting-L09-001', 'football', 'shooting', 'Shooting', 9, 'Shooting L9 Drill 1', 'Shooting practice at level 9.', 23, 'solo', '["ball"]', '["Take 17 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-shooting-L09-002', 'football', 'shooting', 'Shooting', 9, 'Shooting L9 Drill 2', 'Shooting practice at level 9.', 23, 'duo', '["ball"]', '["Take 17 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-shooting-L09-003', 'football', 'shooting', 'Shooting', 9, 'Shooting L9 Drill 3', 'Shooting practice at level 9.', 23, 'solo', '["ball"]', '["Take 17 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-shooting-L10-001', 'football', 'shooting', 'Shooting', 10, 'Shooting L10 Drill 1', 'Shooting practice at level 10.', 25, 'solo', '["ball"]', '["Take 18 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-shooting-L10-002', 'football', 'shooting', 'Shooting', 10, 'Shooting L10 Drill 2', 'Shooting practice at level 10.', 25, 'duo', '["ball"]', '["Take 18 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-shooting-L10-003', 'football', 'shooting', 'Shooting', 10, 'Shooting L10 Drill 3', 'Shooting practice at level 10.', 25, 'solo', '["ball"]', '["Take 18 shots from designated spots. Focus on technique and placement.", "Record makes vs attempts."]', '{"type": "goals", "target": "varies by level", "success_eval": "self_count_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  -- Control L1-L10
  ('football-control-L01-001', 'football', 'control', 'Ball Control', 1, 'Ball Control L1 Drill 1', 'Ball Control practice at level 1.', 7, 'solo', '["ball"]', '["Receive 7 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-control-L01-002', 'football', 'control', 'Ball Control', 1, 'Ball Control L1 Drill 2', 'Ball Control practice at level 1.', 7, 'duo', '["ball"]', '["Receive 7 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-control-L01-003', 'football', 'control', 'Ball Control', 1, 'Ball Control L1 Drill 3', 'Ball Control practice at level 1.', 7, 'solo', '["ball"]', '["Receive 7 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-control-L02-001', 'football', 'control', 'Ball Control', 2, 'Ball Control L2 Drill 1', 'Ball Control practice at level 2.', 9, 'solo', '["ball"]', '["Receive 8 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-control-L02-002', 'football', 'control', 'Ball Control', 2, 'Ball Control L2 Drill 2', 'Ball Control practice at level 2.', 9, 'duo', '["ball"]', '["Receive 8 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-control-L02-003', 'football', 'control', 'Ball Control', 2, 'Ball Control L2 Drill 3', 'Ball Control practice at level 2.', 9, 'solo', '["ball"]', '["Receive 8 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-control-L03-001', 'football', 'control', 'Ball Control', 3, 'Ball Control L3 Drill 1', 'Ball Control practice at level 3.', 11, 'solo', '["ball"]', '["Receive 9 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-control-L03-002', 'football', 'control', 'Ball Control', 3, 'Ball Control L3 Drill 2', 'Ball Control practice at level 3.', 11, 'duo', '["ball"]', '["Receive 9 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-control-L03-003', 'football', 'control', 'Ball Control', 3, 'Ball Control L3 Drill 3', 'Ball Control practice at level 3.', 11, 'solo', '["ball"]', '["Receive 9 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-control-L04-001', 'football', 'control', 'Ball Control', 4, 'Ball Control L4 Drill 1', 'Ball Control practice at level 4.', 13, 'solo', '["ball"]', '["Receive 10 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-control-L04-002', 'football', 'control', 'Ball Control', 4, 'Ball Control L4 Drill 2', 'Ball Control practice at level 4.', 13, 'duo', '["ball"]', '["Receive 10 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-control-L04-003', 'football', 'control', 'Ball Control', 4, 'Ball Control L4 Drill 3', 'Ball Control practice at level 4.', 13, 'solo', '["ball"]', '["Receive 10 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-control-L05-001', 'football', 'control', 'Ball Control', 5, 'Ball Control L5 Drill 1', 'Ball Control practice at level 5.', 15, 'solo', '["ball"]', '["Receive 11 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-control-L05-002', 'football', 'control', 'Ball Control', 5, 'Ball Control L5 Drill 2', 'Ball Control practice at level 5.', 15, 'duo', '["ball"]', '["Receive 11 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-control-L05-003', 'football', 'control', 'Ball Control', 5, 'Ball Control L5 Drill 3', 'Ball Control practice at level 5.', 15, 'solo', '["ball"]', '["Receive 11 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-control-L06-001', 'football', 'control', 'Ball Control', 6, 'Ball Control L6 Drill 1', 'Ball Control practice at level 6.', 17, 'solo', '["ball"]', '["Receive 12 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-control-L06-002', 'football', 'control', 'Ball Control', 6, 'Ball Control L6 Drill 2', 'Ball Control practice at level 6.', 17, 'duo', '["ball"]', '["Receive 12 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-control-L06-003', 'football', 'control', 'Ball Control', 6, 'Ball Control L6 Drill 3', 'Ball Control practice at level 6.', 17, 'solo', '["ball"]', '["Receive 12 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-control-L07-001', 'football', 'control', 'Ball Control', 7, 'Ball Control L7 Drill 1', 'Ball Control practice at level 7.', 19, 'solo', '["ball"]', '["Receive 13 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-control-L07-002', 'football', 'control', 'Ball Control', 7, 'Ball Control L7 Drill 2', 'Ball Control practice at level 7.', 19, 'duo', '["ball"]', '["Receive 13 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-control-L07-003', 'football', 'control', 'Ball Control', 7, 'Ball Control L7 Drill 3', 'Ball Control practice at level 7.', 19, 'solo', '["ball"]', '["Receive 13 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-control-L08-001', 'football', 'control', 'Ball Control', 8, 'Ball Control L8 Drill 1', 'Ball Control practice at level 8.', 21, 'solo', '["ball"]', '["Receive 14 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-control-L08-002', 'football', 'control', 'Ball Control', 8, 'Ball Control L8 Drill 2', 'Ball Control practice at level 8.', 21, 'duo', '["ball"]', '["Receive 14 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-control-L08-003', 'football', 'control', 'Ball Control', 8, 'Ball Control L8 Drill 3', 'Ball Control practice at level 8.', 21, 'solo', '["ball"]', '["Receive 14 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-control-L09-001', 'football', 'control', 'Ball Control', 9, 'Ball Control L9 Drill 1', 'Ball Control practice at level 9.', 23, 'solo', '["ball"]', '["Receive 15 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-control-L09-002', 'football', 'control', 'Ball Control', 9, 'Ball Control L9 Drill 2', 'Ball Control practice at level 9.', 23, 'duo', '["ball"]', '["Receive 15 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-control-L09-003', 'football', 'control', 'Ball Control', 9, 'Ball Control L9 Drill 3', 'Ball Control practice at level 9.', 23, 'solo', '["ball"]', '["Receive 15 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-control-L10-001', 'football', 'control', 'Ball Control', 10, 'Ball Control L10 Drill 1', 'Ball Control practice at level 10.', 25, 'solo', '["ball"]', '["Receive 16 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-control-L10-002', 'football', 'control', 'Ball Control', 10, 'Ball Control L10 Drill 2', 'Ball Control practice at level 10.', 25, 'duo', '["ball"]', '["Receive 16 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-control-L10-003', 'football', 'control', 'Ball Control', 10, 'Ball Control L10 Drill 3', 'Ball Control practice at level 10.', 25, 'solo', '["ball"]', '["Receive 16 passes from partner or rebound off wall; control and pass back.", "Prioritize soft first touch and body positioning."]', '{"type": "first_touch_errors", "target": "<=3 errors", "success_eval": "self_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  -- Fitness L1-L10
  ('football-fitness-L01-001', 'football', 'fitness', 'Fitness & Agility', 1, 'Fitness & Agility L1 Drill 1', 'Fitness & Agility practice at level 1.', 7, 'solo', '["ball", "cones"]', '["Perform 5 sets of agility drills (shuttle runs, ladder, quick-feet) for 7 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-fitness-L01-002', 'football', 'fitness', 'Fitness & Agility', 1, 'Fitness & Agility L1 Drill 2', 'Fitness & Agility practice at level 1.', 7, 'duo', '["ball", "cones"]', '["Perform 5 sets of agility drills (shuttle runs, ladder, quick-feet) for 7 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-fitness-L01-003', 'football', 'fitness', 'Fitness & Agility', 1, 'Fitness & Agility L1 Drill 3', 'Fitness & Agility practice at level 1.', 7, 'solo', '["ball", "cones"]', '["Perform 5 sets of agility drills (shuttle runs, ladder, quick-feet) for 7 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 24, true, 'none'),
  ('football-fitness-L02-001', 'football', 'fitness', 'Fitness & Agility', 2, 'Fitness & Agility L2 Drill 1', 'Fitness & Agility practice at level 2.', 9, 'solo', '["ball", "cones"]', '["Perform 6 sets of agility drills (shuttle runs, ladder, quick-feet) for 9 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-fitness-L02-002', 'football', 'fitness', 'Fitness & Agility', 2, 'Fitness & Agility L2 Drill 2', 'Fitness & Agility practice at level 2.', 9, 'duo', '["ball", "cones"]', '["Perform 6 sets of agility drills (shuttle runs, ladder, quick-feet) for 9 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-fitness-L02-003', 'football', 'fitness', 'Fitness & Agility', 2, 'Fitness & Agility L2 Drill 3', 'Fitness & Agility practice at level 2.', 9, 'solo', '["ball", "cones"]', '["Perform 6 sets of agility drills (shuttle runs, ladder, quick-feet) for 9 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 30, false, 'complete_any_in_category_level_1'),
  ('football-fitness-L03-001', 'football', 'fitness', 'Fitness & Agility', 3, 'Fitness & Agility L3 Drill 1', 'Fitness & Agility practice at level 3.', 11, 'solo', '["ball", "cones"]', '["Perform 7 sets of agility drills (shuttle runs, ladder, quick-feet) for 11 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-fitness-L03-002', 'football', 'fitness', 'Fitness & Agility', 3, 'Fitness & Agility L3 Drill 2', 'Fitness & Agility practice at level 3.', 11, 'duo', '["ball", "cones"]', '["Perform 7 sets of agility drills (shuttle runs, ladder, quick-feet) for 11 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-fitness-L03-003', 'football', 'fitness', 'Fitness & Agility', 3, 'Fitness & Agility L3 Drill 3', 'Fitness & Agility practice at level 3.', 11, 'solo', '["ball", "cones"]', '["Perform 7 sets of agility drills (shuttle runs, ladder, quick-feet) for 11 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 36, false, 'complete_any_in_category_level_2'),
  ('football-fitness-L04-001', 'football', 'fitness', 'Fitness & Agility', 4, 'Fitness & Agility L4 Drill 1', 'Fitness & Agility practice at level 4.', 13, 'solo', '["ball", "cones"]', '["Perform 8 sets of agility drills (shuttle runs, ladder, quick-feet) for 13 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-fitness-L04-002', 'football', 'fitness', 'Fitness & Agility', 4, 'Fitness & Agility L4 Drill 2', 'Fitness & Agility practice at level 4.', 13, 'duo', '["ball", "cones"]', '["Perform 8 sets of agility drills (shuttle runs, ladder, quick-feet) for 13 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-fitness-L04-003', 'football', 'fitness', 'Fitness & Agility', 4, 'Fitness & Agility L4 Drill 3', 'Fitness & Agility practice at level 4.', 13, 'solo', '["ball", "cones"]', '["Perform 8 sets of agility drills (shuttle runs, ladder, quick-feet) for 13 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 42, false, 'complete_any_in_category_level_3'),
  ('football-fitness-L05-001', 'football', 'fitness', 'Fitness & Agility', 5, 'Fitness & Agility L5 Drill 1', 'Fitness & Agility practice at level 5.', 15, 'solo', '["ball", "cones"]', '["Perform 9 sets of agility drills (shuttle runs, ladder, quick-feet) for 15 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-fitness-L05-002', 'football', 'fitness', 'Fitness & Agility', 5, 'Fitness & Agility L5 Drill 2', 'Fitness & Agility practice at level 5.', 15, 'duo', '["ball", "cones"]', '["Perform 9 sets of agility drills (shuttle runs, ladder, quick-feet) for 15 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-fitness-L05-003', 'football', 'fitness', 'Fitness & Agility', 5, 'Fitness & Agility L5 Drill 3', 'Fitness & Agility practice at level 5.', 15, 'solo', '["ball", "cones"]', '["Perform 9 sets of agility drills (shuttle runs, ladder, quick-feet) for 15 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 48, false, 'complete_any_in_category_level_4'),
  ('football-fitness-L06-001', 'football', 'fitness', 'Fitness & Agility', 6, 'Fitness & Agility L6 Drill 1', 'Fitness & Agility practice at level 6.', 17, 'solo', '["ball", "cones"]', '["Perform 10 sets of agility drills (shuttle runs, ladder, quick-feet) for 17 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-fitness-L06-002', 'football', 'fitness', 'Fitness & Agility', 6, 'Fitness & Agility L6 Drill 2', 'Fitness & Agility practice at level 6.', 17, 'duo', '["ball", "cones"]', '["Perform 10 sets of agility drills (shuttle runs, ladder, quick-feet) for 17 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-fitness-L06-003', 'football', 'fitness', 'Fitness & Agility', 6, 'Fitness & Agility L6 Drill 3', 'Fitness & Agility practice at level 6.', 17, 'solo', '["ball", "cones"]', '["Perform 10 sets of agility drills (shuttle runs, ladder, quick-feet) for 17 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 54, false, 'complete_any_in_category_level_5'),
  ('football-fitness-L07-001', 'football', 'fitness', 'Fitness & Agility', 7, 'Fitness & Agility L7 Drill 1', 'Fitness & Agility practice at level 7.', 19, 'solo', '["ball", "cones"]', '["Perform 11 sets of agility drills (shuttle runs, ladder, quick-feet) for 19 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-fitness-L07-002', 'football', 'fitness', 'Fitness & Agility', 7, 'Fitness & Agility L7 Drill 2', 'Fitness & Agility practice at level 7.', 19, 'duo', '["ball", "cones"]', '["Perform 11 sets of agility drills (shuttle runs, ladder, quick-feet) for 19 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-fitness-L07-003', 'football', 'fitness', 'Fitness & Agility', 7, 'Fitness & Agility L7 Drill 3', 'Fitness & Agility practice at level 7.', 19, 'solo', '["ball", "cones"]', '["Perform 11 sets of agility drills (shuttle runs, ladder, quick-feet) for 19 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 60, false, 'complete_any_in_category_level_6'),
  ('football-fitness-L08-001', 'football', 'fitness', 'Fitness & Agility', 8, 'Fitness & Agility L8 Drill 1', 'Fitness & Agility practice at level 8.', 21, 'solo', '["ball", "cones"]', '["Perform 12 sets of agility drills (shuttle runs, ladder, quick-feet) for 21 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-fitness-L08-002', 'football', 'fitness', 'Fitness & Agility', 8, 'Fitness & Agility L8 Drill 2', 'Fitness & Agility practice at level 8.', 21, 'duo', '["ball", "cones"]', '["Perform 12 sets of agility drills (shuttle runs, ladder, quick-feet) for 21 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-fitness-L08-003', 'football', 'fitness', 'Fitness & Agility', 8, 'Fitness & Agility L8 Drill 3', 'Fitness & Agility practice at level 8.', 21, 'solo', '["ball", "cones"]', '["Perform 12 sets of agility drills (shuttle runs, ladder, quick-feet) for 21 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 66, false, 'complete_any_in_category_level_7'),
  ('football-fitness-L09-001', 'football', 'fitness', 'Fitness & Agility', 9, 'Fitness & Agility L9 Drill 1', 'Fitness & Agility practice at level 9.', 23, 'solo', '["ball", "cones"]', '["Perform 13 sets of agility drills (shuttle runs, ladder, quick-feet) for 23 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-fitness-L09-002', 'football', 'fitness', 'Fitness & Agility', 9, 'Fitness & Agility L9 Drill 2', 'Fitness & Agility practice at level 9.', 23, 'duo', '["ball", "cones"]', '["Perform 13 sets of agility drills (shuttle runs, ladder, quick-feet) for 23 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-fitness-L09-003', 'football', 'fitness', 'Fitness & Agility', 9, 'Fitness & Agility L9 Drill 3', 'Fitness & Agility practice at level 9.', 23, 'solo', '["ball", "cones"]', '["Perform 13 sets of agility drills (shuttle runs, ladder, quick-feet) for 23 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 72, false, 'complete_any_in_category_level_8'),
  ('football-fitness-L10-001', 'football', 'fitness', 'Fitness & Agility', 10, 'Fitness & Agility L10 Drill 1', 'Fitness & Agility practice at level 10.', 25, 'solo', '["ball", "cones"]', '["Perform 14 sets of agility drills (shuttle runs, ladder, quick-feet) for 25 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-fitness-L10-002', 'football', 'fitness', 'Fitness & Agility', 10, 'Fitness & Agility L10 Drill 2', 'Fitness & Agility practice at level 10.', 25, 'duo', '["ball", "cones"]', '["Perform 14 sets of agility drills (shuttle runs, ladder, quick-feet) for 25 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9'),
  ('football-fitness-L10-003', 'football', 'fitness', 'Fitness & Agility', 10, 'Fitness & Agility L10 Drill 3', 'Fitness & Agility practice at level 10.', 25, 'solo', '["ball", "cones"]', '["Perform 14 sets of agility drills (shuttle runs, ladder, quick-feet) for 25 minutes total.", "Keep rest short (20-30s) and maintain intensity."]', '{"type": "minutes_or_reps", "target": "Complete sets with required intensity", "success_eval": "self_timer_or_partner", "score_range": [0, 100]}', 78, false, 'complete_any_in_category_level_9')
ON CONFLICT (id) DO UPDATE SET
  sport = EXCLUDED.sport,
  category = EXCLUDED.category,
  category_name = EXCLUDED.category_name,
  level = EXCLUDED.level,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  duration_minutes = EXCLUDED.duration_minutes,
  solo_or_duo = EXCLUDED.solo_or_duo,
  equipment = EXCLUDED.equipment,
  steps = EXCLUDED.steps,
  metric = EXCLUDED.metric,
  xp = EXCLUDED.xp,
  free = EXCLUDED.free,
  unlock_requires = EXCLUDED.unlock_requires,
  updated_at = now();