-- Insert 100 Volleyball drills (5 categories x 20 drills each)
INSERT INTO drills (id, sport, category, category_name, title, description, level, duration_minutes, xp, free, solo_or_duo, unlock_requires) VALUES
-- Serving (20 drills)
('vb-sv-1-1', 'volleyball', 'vb-serving', 'Serving', 'Underhand Serve', 'Basic underhand technique', 1, 8, 25, true, 'solo', 'none'),
('vb-sv-1-2', 'volleyball', 'vb-serving', 'Serving', 'Overhand Toss', 'Consistent ball toss', 1, 8, 25, true, 'solo', 'none'),
('vb-sv-1-3', 'volleyball', 'vb-serving', 'Serving', 'Float Serve Basics', 'Learn float technique', 1, 10, 30, true, 'solo', 'none'),
('vb-sv-1-4', 'volleyball', 'vb-serving', 'Serving', 'Target Zones', 'Aim for court areas', 1, 7, 20, true, 'solo', 'none'),
('vb-sv-2-1', 'volleyball', 'vb-serving', 'Serving', 'Topspin Serve', 'Add topspin for power', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('vb-sv-2-2', 'volleyball', 'vb-serving', 'Serving', 'Jump Serve Start', 'Basic jump serve', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('vb-sv-2-3', 'volleyball', 'vb-serving', 'Serving', 'Short Serve', 'Target front court', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('vb-sv-2-4', 'volleyball', 'vb-serving', 'Serving', 'Deep Corner Serve', 'Target back corners', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('vb-sv-3-1', 'volleyball', 'vb-serving', 'Serving', 'Power Jump Serve', 'Maximum power serve', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('vb-sv-3-2', 'volleyball', 'vb-serving', 'Serving', 'Jump Float', 'Jump float technique', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('vb-sv-3-3', 'volleyball', 'vb-serving', 'Serving', 'Serve Strategy', 'Target weak passers', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-sv-3-4', 'volleyball', 'vb-serving', 'Serving', 'Consistency Drill', '10 serves in a row', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('vb-sv-4-1', 'volleyball', 'vb-serving', 'Serving', 'Pressure Serving', 'Serve under pressure', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-sv-4-2', 'volleyball', 'vb-serving', 'Serving', 'Serve Variation', 'Mix serve types', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('vb-sv-4-3', 'volleyball', 'vb-serving', 'Serving', 'Ace Targeting', 'Serve for aces', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-sv-4-4', 'volleyball', 'vb-serving', 'Serving', 'Clutch Serve', 'Game point serving', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-sv-5-1', 'volleyball', 'vb-serving', 'Serving', 'Elite Jump Serve', 'Pro level power', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-sv-5-2', 'volleyball', 'vb-serving', 'Serving', 'Complete Server', 'All serve types', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('vb-sv-5-3', 'volleyball', 'vb-serving', 'Serving', 'Match Serving', 'Game realistic serves', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('vb-sv-5-4', 'volleyball', 'vb-serving', 'Serving', 'Serve Mastery', 'Full assessment', 5, 25, 80, false, 'solo', 'complete_any_in_category_level_4'),
-- Passing (20 drills)
('vb-ps-1-1', 'volleyball', 'vb-passing', 'Passing', 'Forearm Pass Basics', 'Platform technique', 1, 8, 25, true, 'duo', 'none'),
('vb-ps-1-2', 'volleyball', 'vb-passing', 'Passing', 'Ready Position', 'Athletic stance', 1, 8, 25, true, 'solo', 'none'),
('vb-ps-1-3', 'volleyball', 'vb-passing', 'Passing', 'Shuffle and Pass', 'Move to ball', 1, 10, 30, true, 'duo', 'none'),
('vb-ps-1-4', 'volleyball', 'vb-passing', 'Passing', 'Target Passing', 'Pass to setter zone', 1, 7, 20, true, 'duo', 'none'),
('vb-ps-2-1', 'volleyball', 'vb-passing', 'Passing', 'Serve Receive', 'Pass served balls', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ps-2-2', 'volleyball', 'vb-passing', 'Passing', 'Overhead Pass', 'Set position pass', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ps-2-3', 'volleyball', 'vb-passing', 'Passing', 'Deep Ball Pass', 'Handle deep serves', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ps-2-4', 'volleyball', 'vb-passing', 'Passing', 'Short Ball Pass', 'Handle short serves', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ps-3-1', 'volleyball', 'vb-passing', 'Passing', 'Power Serve Receive', 'Handle hard serves', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ps-3-2', 'volleyball', 'vb-passing', 'Passing', 'Dig Technique', 'Defensive digs', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ps-3-3', 'volleyball', 'vb-passing', 'Passing', 'Platform Angle', 'Control ball direction', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ps-3-4', 'volleyball', 'vb-passing', 'Passing', 'Emergency Pass', 'Desperation saves', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ps-4-1', 'volleyball', 'vb-passing', 'Passing', 'Pressure Passing', 'Pass under pressure', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ps-4-2', 'volleyball', 'vb-passing', 'Passing', 'Pancake Dig', 'Floor save technique', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ps-4-3', 'volleyball', 'vb-passing', 'Passing', 'Chase and Pass', 'Run down balls', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ps-4-4', 'volleyball', 'vb-passing', 'Passing', 'Libero Skills', 'Specialist passing', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ps-5-1', 'volleyball', 'vb-passing', 'Passing', 'Elite Passing', 'Pro level control', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-ps-5-2', 'volleyball', 'vb-passing', 'Passing', 'Perfect Platform', 'Consistent passing', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-ps-5-3', 'volleyball', 'vb-passing', 'Passing', 'Match Passing', 'Game conditions', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('vb-ps-5-4', 'volleyball', 'vb-passing', 'Passing', 'Passing Mastery', 'Full assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),
-- Setting (20 drills)
('vb-st-1-1', 'volleyball', 'vb-setting', 'Setting', 'Hand Position', 'Form the window', 1, 8, 25, true, 'solo', 'none'),
('vb-st-1-2', 'volleyball', 'vb-setting', 'Setting', 'Basic Set', 'Simple overhead set', 1, 8, 25, true, 'duo', 'none'),
('vb-st-1-3', 'volleyball', 'vb-setting', 'Setting', 'Footwork', 'Move under ball', 1, 10, 30, true, 'solo', 'none'),
('vb-st-1-4', 'volleyball', 'vb-setting', 'Setting', 'Front Set', 'Set to outside', 1, 7, 20, true, 'duo', 'none'),
('vb-st-2-1', 'volleyball', 'vb-setting', 'Setting', 'Back Set', 'Set behind you', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('vb-st-2-2', 'volleyball', 'vb-setting', 'Setting', 'Quick Set', 'Fast tempo sets', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('vb-st-2-3', 'volleyball', 'vb-setting', 'Setting', 'Shoot Set', 'Low fast outside', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('vb-st-2-4', 'volleyball', 'vb-setting', 'Setting', 'High Outside', 'Traditional high set', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('vb-st-3-1', 'volleyball', 'vb-setting', 'Setting', 'Dump Set', 'Attack as setter', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-st-3-2', 'volleyball', 'vb-setting', 'Setting', 'Combination Play', 'Multiple hitter options', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-st-3-3', 'volleyball', 'vb-setting', 'Setting', 'Bad Pass Set', 'Set from off net', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-st-3-4', 'volleyball', 'vb-setting', 'Setting', 'Jump Set', 'Set while jumping', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-st-4-1', 'volleyball', 'vb-setting', 'Setting', 'Reading Blockers', 'Set open hitters', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-st-4-2', 'volleyball', 'vb-setting', 'Setting', 'Quick Attack Sync', 'Time middle quick', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-st-4-3', 'volleyball', 'vb-setting', 'Setting', 'Deceptive Setting', 'Freeze blockers', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-st-4-4', 'volleyball', 'vb-setting', 'Setting', 'Pressure Sets', 'Set in tight games', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-st-5-1', 'volleyball', 'vb-setting', 'Setting', 'Elite Setter', 'Pro level setting', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-st-5-2', 'volleyball', 'vb-setting', 'Setting', 'Offensive Leader', 'Run the offense', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-st-5-3', 'volleyball', 'vb-setting', 'Setting', 'Match Setting', 'Game conditions', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('vb-st-5-4', 'volleyball', 'vb-setting', 'Setting', 'Setting Mastery', 'Full assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),
-- Hitting (20 drills)
('vb-ht-1-1', 'volleyball', 'vb-hitting', 'Hitting', 'Arm Swing', 'Basic hitting motion', 1, 8, 25, true, 'solo', 'none'),
('vb-ht-1-2', 'volleyball', 'vb-hitting', 'Hitting', 'Approach Footwork', '3 or 4 step approach', 1, 8, 25, true, 'solo', 'none'),
('vb-ht-1-3', 'volleyball', 'vb-hitting', 'Hitting', 'Contact Point', 'Hit at highest point', 1, 10, 30, true, 'duo', 'none'),
('vb-ht-1-4', 'volleyball', 'vb-hitting', 'Hitting', 'Basic Spike', 'Simple attack', 1, 7, 20, true, 'duo', 'none'),
('vb-ht-2-1', 'volleyball', 'vb-hitting', 'Hitting', 'Line Shot', 'Attack down line', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ht-2-2', 'volleyball', 'vb-hitting', 'Hitting', 'Cross Court', 'Angle attack', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ht-2-3', 'volleyball', 'vb-hitting', 'Hitting', 'Roll Shot', 'Off speed attack', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ht-2-4', 'volleyball', 'vb-hitting', 'Hitting', 'Tip', 'Soft attack over block', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('vb-ht-3-1', 'volleyball', 'vb-hitting', 'Hitting', 'Tool Block', 'Use block to score', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ht-3-2', 'volleyball', 'vb-hitting', 'Hitting', 'Back Row Attack', 'Attack from back', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ht-3-3', 'volleyball', 'vb-hitting', 'Hitting', 'Quick Attack', 'Fast tempo hitting', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ht-3-4', 'volleyball', 'vb-hitting', 'Hitting', 'Transition Hit', 'Attack from defense', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-ht-4-1', 'volleyball', 'vb-hitting', 'Hitting', 'Power Kill', 'Maximum power spike', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ht-4-2', 'volleyball', 'vb-hitting', 'Hitting', 'Shot Selection', 'Read and react', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ht-4-3', 'volleyball', 'vb-hitting', 'Hitting', 'Bad Set Attack', 'Score on off sets', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ht-4-4', 'volleyball', 'vb-hitting', 'Hitting', 'Clutch Hitting', 'Score big points', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-ht-5-1', 'volleyball', 'vb-hitting', 'Hitting', 'Elite Attacker', 'Pro level hitting', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-ht-5-2', 'volleyball', 'vb-hitting', 'Hitting', 'Complete Hitter', 'All attack types', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-ht-5-3', 'volleyball', 'vb-hitting', 'Hitting', 'Match Hitting', 'Game conditions', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('vb-ht-5-4', 'volleyball', 'vb-hitting', 'Hitting', 'Hitting Mastery', 'Full assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),
-- Blocking (20 drills)
('vb-bl-1-1', 'volleyball', 'vb-blocking', 'Blocking', 'Block Position', 'Hands and arms', 1, 8, 25, true, 'solo', 'none'),
('vb-bl-1-2', 'volleyball', 'vb-blocking', 'Blocking', 'Jump Timing', 'When to jump', 1, 8, 25, true, 'duo', 'none'),
('vb-bl-1-3', 'volleyball', 'vb-blocking', 'Blocking', 'Penetration', 'Reach over net', 1, 10, 30, true, 'solo', 'none'),
('vb-bl-1-4', 'volleyball', 'vb-blocking', 'Blocking', 'Single Block', 'Solo blocking', 1, 7, 20, true, 'duo', 'none'),
('vb-bl-2-1', 'volleyball', 'vb-blocking', 'Blocking', 'Double Block', 'Two player block', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('vb-bl-2-2', 'volleyball', 'vb-blocking', 'Blocking', 'Slide Step', 'Move along net', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('vb-bl-2-3', 'volleyball', 'vb-blocking', 'Blocking', 'Crossover Step', 'Fast lateral move', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('vb-bl-2-4', 'volleyball', 'vb-blocking', 'Blocking', 'Read Block', 'React to setter', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('vb-bl-3-1', 'volleyball', 'vb-blocking', 'Blocking', 'Commit Block', 'Jump with quick', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-bl-3-2', 'volleyball', 'vb-blocking', 'Blocking', 'Soft Block', 'Deflect up', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-bl-3-3', 'volleyball', 'vb-blocking', 'Blocking', 'Line Close', 'Take away line', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('vb-bl-3-4', 'volleyball', 'vb-blocking', 'Blocking', 'Angle Seal', 'Close cross court', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('vb-bl-4-1', 'volleyball', 'vb-blocking', 'Blocking', 'Triple Block', 'Three blockers', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-bl-4-2', 'volleyball', 'vb-blocking', 'Blocking', 'Transition Block', 'Block then attack', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-bl-4-3', 'volleyball', 'vb-blocking', 'Blocking', 'Back Row Vision', 'See attack from back', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('vb-bl-4-4', 'volleyball', 'vb-blocking', 'Blocking', 'Joust', 'Win the 50/50', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('vb-bl-5-1', 'volleyball', 'vb-blocking', 'Blocking', 'Elite Blocker', 'Pro level blocking', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-bl-5-2', 'volleyball', 'vb-blocking', 'Blocking', 'Stuff Master', 'Roof attackers', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('vb-bl-5-3', 'volleyball', 'vb-blocking', 'Blocking', 'Match Blocking', 'Game conditions', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('vb-bl-5-4', 'volleyball', 'vb-blocking', 'Blocking', 'Blocking Mastery', 'Full assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4');