-- Insert 100 Padel drills (5 categories x 20 drills each, 4 per level for 5 levels)
INSERT INTO drills (id, sport, category, category_name, title, description, level, duration_minutes, xp, free, solo_or_duo, unlock_requires) VALUES
-- Groundstrokes (20 drills)
('padel-gs-1-1', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Basic Forehand Drive', 'Learn the fundamental padel forehand technique', 1, 8, 25, true, 'solo', 'none'),
('padel-gs-1-2', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Backhand Introduction', 'Master the basic backhand stroke', 1, 8, 25, true, 'solo', 'none'),
('padel-gs-1-3', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Wall Rally Basics', 'Practice basic rallying against the wall', 1, 10, 30, true, 'solo', 'none'),
('padel-gs-1-4', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Ready Position Drills', 'Perfect your ready stance and split step', 1, 7, 20, true, 'solo', 'none'),
('padel-gs-2-1', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Forehand Crosscourt', 'Hit consistent crosscourt forehands', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('padel-gs-2-2', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Backhand Down the Line', 'Control backhand direction down the line', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('padel-gs-2-3', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Low Ball Recovery', 'Handle low bouncing balls effectively', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('padel-gs-2-4', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Side Wall Play', 'Use the side wall to your advantage', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('padel-gs-3-1', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Defensive Lob from Back', 'Execute defensive lobs under pressure', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('padel-gs-3-2', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Chiquita Shot', 'Master the soft low ball over the net', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('padel-gs-3-3', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Double Wall Recovery', 'Handle balls bouncing off two walls', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('padel-gs-3-4', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Deep Return Consistency', 'Return deep balls consistently', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('padel-gs-4-1', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Vibora Counter', 'Counter attack against vibora shots', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('padel-gs-4-2', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Corner Escape Patterns', 'Escape pressure from the corners', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('padel-gs-4-3', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Flat Drive Winner', 'Hit flat winners from baseline', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('padel-gs-4-4', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Back Glass Reading', 'Anticipate and play back glass shots', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('padel-gs-5-1', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Rally Point Construction', 'Build points from baseline strategically', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('padel-gs-5-2', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Glass Shot Master', 'Expert level glass play reading', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('padel-gs-5-3', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Pressure Defense Elite', 'Maintain defense under extreme pressure', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('padel-gs-5-4', 'padel', 'padel-groundstrokes', 'Groundstrokes', 'Complete Ground Game', 'Full groundstroke mastery test', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Volleys (20 drills)
('padel-vo-1-1', 'padel', 'padel-volleys', 'Volleys', 'Forehand Volley Basics', 'Learn the compact forehand volley', 1, 8, 25, true, 'solo', 'none'),
('padel-vo-1-2', 'padel', 'padel-volleys', 'Volleys', 'Backhand Volley Start', 'Master the backhand volley technique', 1, 8, 25, true, 'solo', 'none'),
('padel-vo-1-3', 'padel', 'padel-volleys', 'Volleys', 'Net Position Footwork', 'Move efficiently at the net', 1, 10, 30, true, 'solo', 'none'),
('padel-vo-1-4', 'padel', 'padel-volleys', 'Volleys', 'Soft Volley Touch', 'Develop touch on volley drops', 1, 7, 20, true, 'solo', 'none'),
('padel-vo-2-1', 'padel', 'padel-volleys', 'Volleys', 'Volley to Feet', 'Place volleys at opponents feet', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('padel-vo-2-2', 'padel', 'padel-volleys', 'Volleys', 'High Volley Finish', 'Put away high volleys decisively', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('padel-vo-2-3', 'padel', 'padel-volleys', 'Volleys', 'Reflex Volley Drill', 'Improve reaction time at net', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('padel-vo-2-4', 'padel', 'padel-volleys', 'Volleys', 'Partner Volley Rally', 'Rally volleys with partner at net', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('padel-vo-3-1', 'padel', 'padel-volleys', 'Volleys', 'Bandeja Introduction', 'Learn the signature padel shot', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('padel-vo-3-2', 'padel', 'padel-volleys', 'Volleys', 'Vibora Basics', 'Master the cutting vibora volley', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('padel-vo-3-3', 'padel', 'padel-volleys', 'Volleys', 'Defensive Volley Block', 'Block hard shots back deep', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('padel-vo-3-4', 'padel', 'padel-volleys', 'Volleys', 'Volley Lob Combo', 'Combine volleys with lobs', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('padel-vo-4-1', 'padel', 'padel-volleys', 'Volleys', 'Bandeja Placement', 'Direct bandeja to specific zones', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('padel-vo-4-2', 'padel', 'padel-volleys', 'Volleys', 'Power Vibora', 'Add power to vibora shots', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('padel-vo-4-3', 'padel', 'padel-volleys', 'Volleys', 'Net Domination Pattern', 'Control net position in rallies', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('padel-vo-4-4', 'padel', 'padel-volleys', 'Volleys', 'Fast Hands Drill', 'Quick exchanges at the net', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('padel-vo-5-1', 'padel', 'padel-volleys', 'Volleys', 'Smash Volley Transition', 'Transition from volley to smash', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('padel-vo-5-2', 'padel', 'padel-volleys', 'Volleys', 'Elite Bandeja Patterns', 'Advanced bandeja shot patterns', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('padel-vo-5-3', 'padel', 'padel-volleys', 'Volleys', 'Pressure Net Finish', 'Close out points at the net', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('padel-vo-5-4', 'padel', 'padel-volleys', 'Volleys', 'Complete Volley Arsenal', 'Full volley mastery assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Smash (20 drills)
('padel-sm-1-1', 'padel', 'padel-smash', 'Smash', 'Basic Overhead Smash', 'Learn fundamental smash technique', 1, 8, 25, true, 'solo', 'none'),
('padel-sm-1-2', 'padel', 'padel-smash', 'Smash', 'Positioning for Smash', 'Get under the ball correctly', 1, 8, 25, true, 'solo', 'none'),
('padel-sm-1-3', 'padel', 'padel-smash', 'Smash', 'Controlled Power Smash', 'Add control before power', 1, 10, 30, true, 'solo', 'none'),
('padel-sm-1-4', 'padel', 'padel-smash', 'Smash', 'Target Practice Smash', 'Hit smash to specific zones', 1, 7, 20, true, 'solo', 'none'),
('padel-sm-2-1', 'padel', 'padel-smash', 'Smash', 'Smash Off Glass', 'Smash after wall bounce', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('padel-sm-2-2', 'padel', 'padel-smash', 'Smash', 'Directional Smash', 'Choose smash direction', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('padel-sm-2-3', 'padel', 'padel-smash', 'Smash', 'Deep Smash Recovery', 'Handle deep lobs with smash', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('padel-sm-2-4', 'padel', 'padel-smash', 'Smash', 'Smash and Net Follow', 'Approach net after smash', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('padel-sm-3-1', 'padel', 'padel-smash', 'Smash', 'Por Tres Smash', 'Hit the signature out-of-court winner', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sm-3-2', 'padel', 'padel-smash', 'Smash', 'Gancho Introduction', 'Learn the hook smash technique', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sm-3-3', 'padel', 'padel-smash', 'Smash', 'Moving Smash', 'Smash while on the move', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sm-3-4', 'padel', 'padel-smash', 'Smash', 'Flat vs Spin Smash', 'Choose flat or topspin smash', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sm-4-1', 'padel', 'padel-smash', 'Smash', 'Por Cuatro Setup', 'Position for four-wall winner', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('padel-sm-4-2', 'padel', 'padel-smash', 'Smash', 'Advanced Gancho', 'Hook smash with power', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('padel-sm-4-3', 'padel', 'padel-smash', 'Smash', 'Jump Smash Power', 'Add jump to maximize power', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('padel-sm-4-4', 'padel', 'padel-smash', 'Smash', 'Smash Under Pressure', 'Execute smash when tired', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('padel-sm-5-1', 'padel', 'padel-smash', 'Smash', 'Elite Por Tres Winner', 'Consistent out-of-court winners', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('padel-sm-5-2', 'padel', 'padel-smash', 'Smash', 'Smash Point Finish', 'End points with decisive smash', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('padel-sm-5-3', 'padel', 'padel-smash', 'Smash', 'Any Ball Smash', 'Smash from any position', 5, 22, 75, false, 'solo', 'complete_any_in_category_level_4'),
('padel-sm-5-4', 'padel', 'padel-smash', 'Smash', 'Complete Smash Mastery', 'Full smash assessment test', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Serve (20 drills)
('padel-sv-1-1', 'padel', 'padel-serve', 'Serve', 'Underhand Serve Basics', 'Learn the legal padel serve', 1, 8, 25, true, 'solo', 'none'),
('padel-sv-1-2', 'padel', 'padel-serve', 'Serve', 'Serve Placement Start', 'Aim serves to the T or wide', 1, 8, 25, true, 'solo', 'none'),
('padel-sv-1-3', 'padel', 'padel-serve', 'Serve', 'Consistent Serve Height', 'Control serve trajectory', 1, 10, 30, true, 'solo', 'none'),
('padel-sv-1-4', 'padel', 'padel-serve', 'Serve', 'Serve and Position', 'Move to net after serve', 1, 7, 20, true, 'solo', 'none'),
('padel-sv-2-1', 'padel', 'padel-serve', 'Serve', 'Slice Serve Introduction', 'Add sidespin to serve', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('padel-sv-2-2', 'padel', 'padel-serve', 'Serve', 'Deep Serve Consistency', 'Serve deep into box', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('padel-sv-2-3', 'padel', 'padel-serve', 'Serve', 'Body Serve Target', 'Aim serves at receiver body', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('padel-sv-2-4', 'padel', 'padel-serve', 'Serve', 'First Volley Setup', 'Serve plus first volley combo', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('padel-sv-3-1', 'padel', 'padel-serve', 'Serve', 'Wall Serve Kick', 'Use glass wall on serve', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sv-3-2', 'padel', 'padel-serve', 'Serve', 'Variation Serve Pattern', 'Mix up serve types', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sv-3-3', 'padel', 'padel-serve', 'Serve', 'Second Serve Safety', 'Reliable second serve', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sv-3-4', 'padel', 'padel-serve', 'Serve', 'Wide Angle Serve', 'Extreme angle serves', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('padel-sv-4-1', 'padel', 'padel-serve', 'Serve', 'Power Serve Control', 'Add pace while maintaining accuracy', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('padel-sv-4-2', 'padel', 'padel-serve', 'Serve', 'Serve Disguise', 'Hide serve direction', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('padel-sv-4-3', 'padel', 'padel-serve', 'Serve', 'Return Anticipation', 'Read return after serve', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('padel-sv-4-4', 'padel', 'padel-serve', 'Serve', 'Pressure Serve Routine', 'Maintain serve under pressure', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('padel-sv-5-1', 'padel', 'padel-serve', 'Serve', 'Ace Serve Pattern', 'Serve unreturnable balls', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('padel-sv-5-2', 'padel', 'padel-serve', 'Serve', 'Complete Serve Arsenal', 'All serve types mastered', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('padel-sv-5-3', 'padel', 'padel-serve', 'Serve', 'Match Simulation Serve', 'Serve in match conditions', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('padel-sv-5-4', 'padel', 'padel-serve', 'Serve', 'Serve Mastery Test', 'Full serve assessment', 5, 25, 80, false, 'solo', 'complete_any_in_category_level_4'),

-- Strategy (20 drills)
('padel-st-1-1', 'padel', 'padel-strategy', 'Strategy', 'Court Position Basics', 'Learn the 4 court zones', 1, 8, 25, true, 'solo', 'none'),
('padel-st-1-2', 'padel', 'padel-strategy', 'Strategy', 'Partner Communication', 'Basic call and response', 1, 8, 25, true, 'duo', 'none'),
('padel-st-1-3', 'padel', 'padel-strategy', 'Strategy', 'Net vs Back Decision', 'When to move forward', 1, 10, 30, true, 'duo', 'none'),
('padel-st-1-4', 'padel', 'padel-strategy', 'Strategy', 'Rally Patience', 'Build points slowly', 1, 7, 20, true, 'duo', 'none'),
('padel-st-2-1', 'padel', 'padel-strategy', 'Strategy', 'Parallel Movement', 'Move with partner in sync', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('padel-st-2-2', 'padel', 'padel-strategy', 'Strategy', 'Golden Point Strategy', 'Handle sudden death points', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('padel-st-2-3', 'padel', 'padel-strategy', 'Strategy', 'Lob vs Drive Choice', 'Shot selection from back', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('padel-st-2-4', 'padel', 'padel-strategy', 'Strategy', 'Defense to Attack', 'Transition from defense', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('padel-st-3-1', 'padel', 'padel-strategy', 'Strategy', 'Weak Side Targeting', 'Find opponent weaknesses', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('padel-st-3-2', 'padel', 'padel-strategy', 'Strategy', 'Switch Play Pattern', 'Change attack direction', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('padel-st-3-3', 'padel', 'padel-strategy', 'Strategy', 'Poach Timing', 'When to intercept', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('padel-st-3-4', 'padel', 'padel-strategy', 'Strategy', 'Return Game Plan', 'Strategy on return games', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('padel-st-4-1', 'padel', 'padel-strategy', 'Strategy', 'Advanced Formations', 'Australian and I formations', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('padel-st-4-2', 'padel', 'padel-strategy', 'Strategy', 'Momentum Control', 'Manage match momentum', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('padel-st-4-3', 'padel', 'padel-strategy', 'Strategy', 'Pattern Play Execution', 'Run set plays with partner', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('padel-st-4-4', 'padel', 'padel-strategy', 'Strategy', 'Opponent Reading', 'Anticipate opponent shots', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('padel-st-5-1', 'padel', 'padel-strategy', 'Strategy', 'Elite Point Construction', 'Build perfect points', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('padel-st-5-2', 'padel', 'padel-strategy', 'Strategy', 'Match Management', 'Complete match strategy', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('padel-st-5-3', 'padel', 'padel-strategy', 'Strategy', 'Doubles Synergy', 'Perfect partner coordination', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('padel-st-5-4', 'padel', 'padel-strategy', 'Strategy', 'Complete Padel IQ', 'Full strategy mastery test', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4');