-- ============================================================
-- GOLF DRILLS (100 total: 5 categories x 5 levels x 4 drills)
-- ============================================================

-- Putting (Levels 1-5, 4 drills each = 20)
INSERT INTO public.drills (id, sport, category, category_name, level, title, description, duration_minutes, xp, free, unlock_requires) VALUES
('golf-putting-L01-001', 'golf', 'golf-putting', 'Putting', 1, 'Basic Putt Stance', 'Learn the fundamental putting stance for consistent strokes', 7, 30, true, 'none'),
('golf-putting-L01-002', 'golf', 'golf-putting', 'Putting', 1, 'Short Putt Practice', 'Master 3-foot putts with proper alignment', 7, 30, true, 'none'),
('golf-putting-L01-003', 'golf', 'golf-putting', 'Putting', 1, 'Pendulum Motion', 'Develop smooth pendulum putting motion', 7, 30, true, 'none'),
('golf-putting-L01-004', 'golf', 'golf-putting', 'Putting', 1, 'Eye Line Drill', 'Practice keeping eyes over the ball', 7, 30, true, 'none'),
('golf-putting-L02-001', 'golf', 'golf-putting', 'Putting', 2, 'Distance Control Basics', 'Learn to control putt distance on flat greens', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-putting-L02-002', 'golf', 'golf-putting', 'Putting', 2, 'Gate Drill', 'Improve accuracy with tee gate practice', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-putting-L02-003', 'golf', 'golf-putting', 'Putting', 2, 'Clock Drill', 'Circle putt practice from all angles', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-putting-L02-004', 'golf', 'golf-putting', 'Putting', 2, 'Lag Putting Intro', 'Introduction to long-distance putting', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-putting-L03-001', 'golf', 'golf-putting', 'Putting', 3, 'Breaking Putts Left', 'Read and execute left-breaking putts', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-putting-L03-002', 'golf', 'golf-putting', 'Putting', 3, 'Breaking Putts Right', 'Read and execute right-breaking putts', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-putting-L03-003', 'golf', 'golf-putting', 'Putting', 3, 'Uphill Putts', 'Master uphill putting technique', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-putting-L03-004', 'golf', 'golf-putting', 'Putting', 3, 'Downhill Putts', 'Control speed on downhill putts', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-putting-L04-001', 'golf', 'golf-putting', 'Putting', 4, 'Double Break Reads', 'Navigate putts with multiple breaks', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-putting-L04-002', 'golf', 'golf-putting', 'Putting', 4, 'Pressure Putting', 'Practice under simulated pressure', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-putting-L04-003', 'golf', 'golf-putting', 'Putting', 4, 'Speed Reading', 'Judge green speed accurately', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-putting-L04-004', 'golf', 'golf-putting', 'Putting', 4, 'Ladder Drill Advanced', 'Progressive distance putting challenge', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-putting-L05-001', 'golf', 'golf-putting', 'Putting', 5, 'Competition Simulation', 'Tournament-style putting scenarios', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-putting-L05-002', 'golf', 'golf-putting', 'Putting', 5, 'Extreme Slopes', 'Master severely sloped greens', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-putting-L05-003', 'golf', 'golf-putting', 'Putting', 5, 'Clutch Putting', 'Game-winning putt scenarios', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-putting-L05-004', 'golf', 'golf-putting', 'Putting', 5, 'Green Reading Mastery', 'Advanced green reading techniques', 12, 50, false, 'complete_any_in_category_level_4'),

-- Driving (Levels 1-5, 4 drills each = 20)
('golf-driving-L01-001', 'golf', 'golf-driving', 'Driving', 1, 'Grip Fundamentals', 'Learn proper driving grip technique', 7, 30, true, 'none'),
('golf-driving-L01-002', 'golf', 'golf-driving', 'Driving', 1, 'Stance and Posture', 'Set up correctly for powerful drives', 7, 30, true, 'none'),
('golf-driving-L01-003', 'golf', 'golf-driving', 'Driving', 1, 'Basic Swing Path', 'Develop a smooth backswing and follow-through', 7, 30, true, 'none'),
('golf-driving-L01-004', 'golf', 'golf-driving', 'Driving', 1, 'Ball Position', 'Optimal ball placement for drives', 7, 30, true, 'none'),
('golf-driving-L02-001', 'golf', 'golf-driving', 'Driving', 2, 'Weight Transfer', 'Power through proper weight shift', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-driving-L02-002', 'golf', 'golf-driving', 'Driving', 2, 'Hip Rotation Drill', 'Generate power from hip turn', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-driving-L02-003', 'golf', 'golf-driving', 'Driving', 2, 'Tempo Training', 'Develop consistent swing tempo', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-driving-L02-004', 'golf', 'golf-driving', 'Driving', 2, 'Alignment Sticks', 'Use alignment aids for accuracy', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-driving-L03-001', 'golf', 'golf-driving', 'Driving', 3, 'Draw Shot', 'Learn to hit a controlled draw', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-driving-L03-002', 'golf', 'golf-driving', 'Driving', 3, 'Fade Shot', 'Master the controlled fade', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-driving-L03-003', 'golf', 'golf-driving', 'Driving', 3, 'Low Punch Drive', 'Drive under wind conditions', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-driving-L03-004', 'golf', 'golf-driving', 'Driving', 3, 'Power Drill', 'Increase driving distance safely', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-driving-L04-001', 'golf', 'golf-driving', 'Driving', 4, 'Fairway Finder', 'Accuracy over distance training', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-driving-L04-002', 'golf', 'golf-driving', 'Driving', 4, 'Wind Play', 'Adjust drives for various wind', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-driving-L04-003', 'golf', 'golf-driving', 'Driving', 4, 'Elevation Changes', 'Drive on uphill and downhill lies', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-driving-L04-004', 'golf', 'golf-driving', 'Driving', 4, 'Pressure Tee Shots', 'Perform under simulated pressure', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-driving-L05-001', 'golf', 'golf-driving', 'Driving', 5, 'Course Strategy', 'Match drive shape to hole layout', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-driving-L05-002', 'golf', 'golf-driving', 'Driving', 5, 'Maximum Distance', 'Optimize for carry and roll', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-driving-L05-003', 'golf', 'golf-driving', 'Driving', 5, 'Trouble Recovery', 'Recovery drives from rough', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-driving-L05-004', 'golf', 'golf-driving', 'Driving', 5, 'Tournament Ready', 'Full pre-round driving warm-up', 12, 50, false, 'complete_any_in_category_level_4'),

-- Chipping (Levels 1-5, 4 drills each = 20)
('golf-chipping-L01-001', 'golf', 'golf-chipping', 'Chipping', 1, 'Basic Chip Setup', 'Fundamental chipping stance and grip', 7, 30, true, 'none'),
('golf-chipping-L01-002', 'golf', 'golf-chipping', 'Chipping', 1, 'Bump and Run', 'Low running chip technique', 7, 30, true, 'none'),
('golf-chipping-L01-003', 'golf', 'golf-chipping', 'Chipping', 1, 'Landing Spot Focus', 'Pick and hit landing targets', 7, 30, true, 'none'),
('golf-chipping-L01-004', 'golf', 'golf-chipping', 'Chipping', 1, 'Short Chip Practice', 'Chips from just off the green', 7, 30, true, 'none'),
('golf-chipping-L02-001', 'golf', 'golf-chipping', 'Chipping', 2, 'Club Selection', 'Choose right club for chip type', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-chipping-L02-002', 'golf', 'golf-chipping', 'Chipping', 2, 'High Loft Chips', 'Stop the ball quickly', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-chipping-L02-003', 'golf', 'golf-chipping', 'Chipping', 2, 'Uphill Chips', 'Adjust for uphill lies', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-chipping-L02-004', 'golf', 'golf-chipping', 'Chipping', 2, 'Downhill Chips', 'Control on downhill lies', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-chipping-L03-001', 'golf', 'golf-chipping', 'Chipping', 3, 'Flop Shot Basics', 'High soft landing chips', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-chipping-L03-002', 'golf', 'golf-chipping', 'Chipping', 3, 'Tight Lies', 'Chip from hardpan and bare lies', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-chipping-L03-003', 'golf', 'golf-chipping', 'Chipping', 3, 'Rough Chips', 'Extract from thick grass', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-chipping-L03-004', 'golf', 'golf-chipping', 'Chipping', 3, 'Spin Control', 'Add backspin to chips', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-chipping-L04-001', 'golf', 'golf-chipping', 'Chipping', 4, 'Sidehill Chips', 'Ball above and below feet', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-chipping-L04-002', 'golf', 'golf-chipping', 'Chipping', 4, 'Combination Chips', 'Navigate breaks after landing', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-chipping-L04-003', 'golf', 'golf-chipping', 'Chipping', 4, 'Long Chip Mastery', 'Chips from 30+ yards', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-chipping-L04-004', 'golf', 'golf-chipping', 'Chipping', 4, 'Pressure Chips', 'Up-and-down under pressure', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-chipping-L05-001', 'golf', 'golf-chipping', 'Chipping', 5, 'Phil Flop', 'Extreme high loft shot', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-chipping-L05-002', 'golf', 'golf-chipping', 'Chipping', 5, 'Multi-Tier Greens', 'Chip to different levels', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-chipping-L05-003', 'golf', 'golf-chipping', 'Chipping', 5, 'Creative Shots', 'Unorthodox chip solutions', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-chipping-L05-004', 'golf', 'golf-chipping', 'Chipping', 5, 'Tour Level Chipping', 'PGA-level short game drills', 12, 50, false, 'complete_any_in_category_level_4'),

-- Iron Play (Levels 1-5, 4 drills each = 20)
('golf-iron-play-L01-001', 'golf', 'golf-iron-play', 'Iron Play', 1, 'Iron Grip', 'Proper grip for iron shots', 7, 30, true, 'none'),
('golf-iron-play-L01-002', 'golf', 'golf-iron-play', 'Iron Play', 1, 'Ball First Contact', 'Strike ball before turf', 7, 30, true, 'none'),
('golf-iron-play-L01-003', 'golf', 'golf-iron-play', 'Iron Play', 1, 'Short Iron Basics', 'PW and 9-iron fundamentals', 7, 30, true, 'none'),
('golf-iron-play-L01-004', 'golf', 'golf-iron-play', 'Iron Play', 1, 'Target Practice', 'Aim at specific targets', 7, 30, true, 'none'),
('golf-iron-play-L02-001', 'golf', 'golf-iron-play', 'Iron Play', 2, 'Mid Iron Control', '7-iron and 6-iron drills', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-iron-play-L02-002', 'golf', 'golf-iron-play', 'Iron Play', 2, 'Divot Pattern', 'Consistent divot after ball', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-iron-play-L02-003', 'golf', 'golf-iron-play', 'Iron Play', 2, 'Distance Gapping', 'Know your club distances', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-iron-play-L02-004', 'golf', 'golf-iron-play', 'Iron Play', 2, 'Punch Shots', 'Low trajectory approach', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-iron-play-L03-001', 'golf', 'golf-iron-play', 'Iron Play', 3, 'Long Irons', '4-iron and 5-iron mastery', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-iron-play-L03-002', 'golf', 'golf-iron-play', 'Iron Play', 3, 'Shot Shaping', 'Draw and fade with irons', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-iron-play-L03-003', 'golf', 'golf-iron-play', 'Iron Play', 3, 'Partial Swings', 'Three-quarter and half shots', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-iron-play-L03-004', 'golf', 'golf-iron-play', 'Iron Play', 3, 'Rough Recovery', 'Irons from the rough', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-iron-play-L04-001', 'golf', 'golf-iron-play', 'Iron Play', 4, 'Knockdown Shots', 'Controlled low flight', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-iron-play-L04-002', 'golf', 'golf-iron-play', 'Iron Play', 4, 'Uneven Lies', 'Sidehill and slope shots', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-iron-play-L04-003', 'golf', 'golf-iron-play', 'Iron Play', 4, 'Pin Seeking', 'Attack tight pin positions', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-iron-play-L04-004', 'golf', 'golf-iron-play', 'Iron Play', 4, 'Wind Adjustments', 'Club up/down in wind', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-iron-play-L05-001', 'golf', 'golf-iron-play', 'Iron Play', 5, 'Stinger Shot', 'Tiger-style low iron', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-iron-play-L05-002', 'golf', 'golf-iron-play', 'Iron Play', 5, 'Pressure Approaches', 'Critical approach shots', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-iron-play-L05-003', 'golf', 'golf-iron-play', 'Iron Play', 5, 'Scoring Zone', 'Inside 150 yard mastery', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-iron-play-L05-004', 'golf', 'golf-iron-play', 'Iron Play', 5, 'Course Management', 'Strategic iron selection', 12, 50, false, 'complete_any_in_category_level_4'),

-- Bunker Shots (Levels 1-5, 4 drills each = 20)
('golf-bunker-L01-001', 'golf', 'golf-bunker', 'Bunker Shots', 1, 'Bunker Setup', 'Open stance and club face', 7, 30, true, 'none'),
('golf-bunker-L01-002', 'golf', 'golf-bunker', 'Bunker Shots', 1, 'Sand Entry Point', 'Enter sand behind ball', 7, 30, true, 'none'),
('golf-bunker-L01-003', 'golf', 'golf-bunker', 'Bunker Shots', 1, 'Splash Out', 'Basic greenside bunker exit', 7, 30, true, 'none'),
('golf-bunker-L01-004', 'golf', 'golf-bunker', 'Bunker Shots', 1, 'Follow Through', 'Complete the bunker swing', 7, 30, true, 'none'),
('golf-bunker-L02-001', 'golf', 'golf-bunker', 'Bunker Shots', 2, 'Distance Control', 'Vary bunker shot length', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-bunker-L02-002', 'golf', 'golf-bunker', 'Bunker Shots', 2, 'Soft Landing', 'High soft bunker shots', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-bunker-L02-003', 'golf', 'golf-bunker', 'Bunker Shots', 2, 'Running Bunker', 'Low running bunker escape', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-bunker-L02-004', 'golf', 'golf-bunker', 'Bunker Shots', 2, 'Uphill Bunker', 'Ball above feet in sand', 8, 35, false, 'complete_any_in_category_level_1'),
('golf-bunker-L03-001', 'golf', 'golf-bunker', 'Bunker Shots', 3, 'Downhill Bunker', 'Ball below feet challenge', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-bunker-L03-002', 'golf', 'golf-bunker', 'Bunker Shots', 3, 'Plugged Lie', 'Fried egg recovery', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-bunker-L03-003', 'golf', 'golf-bunker', 'Bunker Shots', 3, 'Wet Sand', 'Adjust for firm sand', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-bunker-L03-004', 'golf', 'golf-bunker', 'Bunker Shots', 3, 'Long Bunker', '40+ yard bunker shots', 9, 40, false, 'complete_any_in_category_level_2'),
('golf-bunker-L04-001', 'golf', 'golf-bunker', 'Bunker Shots', 4, 'Fairway Bunker', 'Clean contact from fairway sand', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-bunker-L04-002', 'golf', 'golf-bunker', 'Bunker Shots', 4, 'High Lip Escape', 'Clear steep bunker faces', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-bunker-L04-003', 'golf', 'golf-bunker', 'Bunker Shots', 4, 'Awkward Stances', 'Uneven bunker lies', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-bunker-L04-004', 'golf', 'golf-bunker', 'Bunker Shots', 4, 'Spin from Sand', 'Check and release control', 10, 45, false, 'complete_any_in_category_level_3'),
('golf-bunker-L05-001', 'golf', 'golf-bunker', 'Bunker Shots', 5, 'Seve Shots', 'Creative bunker escapes', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-bunker-L05-002', 'golf', 'golf-bunker', 'Bunker Shots', 5, 'No Look Bunker', 'Trust your technique', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-bunker-L05-003', 'golf', 'golf-bunker', 'Bunker Shots', 5, 'Pressure Sand Saves', 'Must-make bunker shots', 12, 50, false, 'complete_any_in_category_level_4'),
('golf-bunker-L05-004', 'golf', 'golf-bunker', 'Bunker Shots', 5, 'Master Class Bunker', 'Tour-level sand play', 12, 50, false, 'complete_any_in_category_level_4')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description;