-- ============================================================
-- CRICKET, PADEL, RUGBY DRILLS (100 each = 300 total)
-- ============================================================

-- CRICKET DRILLS
INSERT INTO public.drills (id, sport, category, category_name, level, title, description, duration_minutes, xp, free, unlock_requires) VALUES
-- Batting
('cricket-batting-L01-001', 'cricket', 'cricket-batting', 'Batting', 1, 'Grip and Stance', 'Proper bat hold and ready position', 7, 30, true, 'none'),
('cricket-batting-L01-002', 'cricket', 'cricket-batting', 'Batting', 1, 'Forward Defense', 'Block front foot deliveries', 7, 30, true, 'none'),
('cricket-batting-L01-003', 'cricket', 'cricket-batting', 'Batting', 1, 'Back Foot Defense', 'Handle short balls', 7, 30, true, 'none'),
('cricket-batting-L01-004', 'cricket', 'cricket-batting', 'Batting', 1, 'Straight Drive', 'Classic cricket shot', 7, 30, true, 'none'),
('cricket-batting-L02-001', 'cricket', 'cricket-batting', 'Batting', 2, 'Cover Drive', 'Through the covers', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-batting-L02-002', 'cricket', 'cricket-batting', 'Batting', 2, 'Pull Shot', 'Attack short balls', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-batting-L02-003', 'cricket', 'cricket-batting', 'Batting', 2, 'Cut Shot', 'Square of the wicket', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-batting-L02-004', 'cricket', 'cricket-batting', 'Batting', 2, 'Leave Drill', 'Know what to leave', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-batting-L03-001', 'cricket', 'cricket-batting', 'Batting', 3, 'Sweep Shot', 'Get down to spin', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-batting-L03-002', 'cricket', 'cricket-batting', 'Batting', 3, 'Flick Off Pads', 'Work it to leg side', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-batting-L03-003', 'cricket', 'cricket-batting', 'Batting', 3, 'Late Cut', 'Use pace against bowler', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-batting-L03-004', 'cricket', 'cricket-batting', 'Batting', 3, 'Spin Reading', 'Identify spin types', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-batting-L04-001', 'cricket', 'cricket-batting', 'Batting', 4, 'Reverse Sweep', 'Switch hit basics', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-batting-L04-002', 'cricket', 'cricket-batting', 'Batting', 4, 'Lofted Drive', 'Hit over the top', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-batting-L04-003', 'cricket', 'cricket-batting', 'Batting', 4, 'Hook Shot', 'Against bouncers', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-batting-L04-004', 'cricket', 'cricket-batting', 'Batting', 4, 'Partnership Building', 'Run between wickets', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-batting-L05-001', 'cricket', 'cricket-batting', 'Batting', 5, 'Scoop Shot', 'Unorthodox power', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-batting-L05-002', 'cricket', 'cricket-batting', 'Batting', 5, 'Death Over Batting', 'Score under pressure', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-batting-L05-003', 'cricket', 'cricket-batting', 'Batting', 5, 'Match Situation', 'Adapt to game state', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-batting-L05-004', 'cricket', 'cricket-batting', 'Batting', 5, 'Complete Batsman', 'All shots mastery', 12, 50, false, 'complete_any_in_category_level_4'),

-- Bowling
('cricket-bowling-L01-001', 'cricket', 'cricket-bowling', 'Bowling', 1, 'Basic Action', 'Smooth bowling action', 7, 30, true, 'none'),
('cricket-bowling-L01-002', 'cricket', 'cricket-bowling', 'Bowling', 1, 'Line and Length', 'Hit the good length', 7, 30, true, 'none'),
('cricket-bowling-L01-003', 'cricket', 'cricket-bowling', 'Bowling', 1, 'Seam Position', 'Present the seam', 7, 30, true, 'none'),
('cricket-bowling-L01-004', 'cricket', 'cricket-bowling', 'Bowling', 1, 'Run Up Rhythm', 'Consistent approach', 7, 30, true, 'none'),
('cricket-bowling-L02-001', 'cricket', 'cricket-bowling', 'Bowling', 2, 'Outswing', 'Move ball away', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-bowling-L02-002', 'cricket', 'cricket-bowling', 'Bowling', 2, 'Inswing', 'Bring ball in', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-bowling-L02-003', 'cricket', 'cricket-bowling', 'Bowling', 2, 'Yorker', 'Full at the stumps', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-bowling-L02-004', 'cricket', 'cricket-bowling', 'Bowling', 2, 'Short Ball', 'Bouncer technique', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-bowling-L03-001', 'cricket', 'cricket-bowling', 'Bowling', 3, 'Off Spin', 'Turn off the pitch', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-bowling-L03-002', 'cricket', 'cricket-bowling', 'Bowling', 3, 'Leg Spin', 'Spin the other way', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-bowling-L03-003', 'cricket', 'cricket-bowling', 'Bowling', 3, 'Slower Ball', 'Change of pace', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-bowling-L03-004', 'cricket', 'cricket-bowling', 'Bowling', 3, 'Cutters', 'Off and leg cutter', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-bowling-L04-001', 'cricket', 'cricket-bowling', 'Bowling', 4, 'Reverse Swing', 'Old ball movement', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-bowling-L04-002', 'cricket', 'cricket-bowling', 'Bowling', 4, 'Doosra/Carrom', 'Spin variations', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-bowling-L04-003', 'cricket', 'cricket-bowling', 'Bowling', 4, 'Bowling Plans', 'Set batsman up', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-bowling-L04-004', 'cricket', 'cricket-bowling', 'Bowling', 4, 'Wide Yorkers', 'Death bowling', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-bowling-L05-001', 'cricket', 'cricket-bowling', 'Bowling', 5, 'Bumrah Yorker', 'Toe-crushing delivery', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-bowling-L05-002', 'cricket', 'cricket-bowling', 'Bowling', 5, 'Match Winning Spell', 'Pressure bowling', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-bowling-L05-003', 'cricket', 'cricket-bowling', 'Bowling', 5, 'Spell Management', 'Pace yourself', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-bowling-L05-004', 'cricket', 'cricket-bowling', 'Bowling', 5, 'Complete Bowler', 'All deliveries', 12, 50, false, 'complete_any_in_category_level_4'),

-- Fielding
('cricket-fielding-L01-001', 'cricket', 'cricket-fielding', 'Fielding', 1, 'Ground Fielding', 'Clean pick up', 7, 30, true, 'none'),
('cricket-fielding-L01-002', 'cricket', 'cricket-fielding', 'Fielding', 1, 'Catching Basics', 'Safe hands', 7, 30, true, 'none'),
('cricket-fielding-L01-003', 'cricket', 'cricket-fielding', 'Fielding', 1, 'Throwing Accuracy', 'Hit the stumps', 7, 30, true, 'none'),
('cricket-fielding-L01-004', 'cricket', 'cricket-fielding', 'Fielding', 1, 'Backing Up', 'Support teammates', 7, 30, true, 'none'),
('cricket-fielding-L02-001', 'cricket', 'cricket-fielding', 'Fielding', 2, 'High Catches', 'Under the ball', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-fielding-L02-002', 'cricket', 'cricket-fielding', 'Fielding', 2, 'Diving Saves', 'Full stretch stops', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-fielding-L02-003', 'cricket', 'cricket-fielding', 'Fielding', 2, 'Direct Hit', 'Run out attempts', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-fielding-L02-004', 'cricket', 'cricket-fielding', 'Fielding', 2, 'Relay Throws', 'Chain the ball', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-fielding-L03-001', 'cricket', 'cricket-fielding', 'Fielding', 3, 'Slip Catching', 'Edge catches', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-fielding-L03-002', 'cricket', 'cricket-fielding', 'Fielding', 3, 'Boundary Fielding', 'Stops at the rope', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-fielding-L03-003', 'cricket', 'cricket-fielding', 'Fielding', 3, 'Close Catching', 'Short leg and silly point', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-fielding-L03-004', 'cricket', 'cricket-fielding', 'Fielding', 3, 'Sliding Stop', 'Save boundaries', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-fielding-L04-001', 'cricket', 'cricket-fielding', 'Fielding', 4, 'Catch Off Balance', 'Acrobatic catches', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-fielding-L04-002', 'cricket', 'cricket-fielding', 'Fielding', 4, 'Boundary Catch', 'Near the rope', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-fielding-L04-003', 'cricket', 'cricket-fielding', 'Fielding', 4, 'Pressure Fielding', 'Last over situations', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-fielding-L04-004', 'cricket', 'cricket-fielding', 'Fielding', 4, 'Quick Returns', 'Prevent second run', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-fielding-L05-001', 'cricket', 'cricket-fielding', 'Fielding', 5, 'Jonty Rhodes Style', 'Spectacular saves', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-fielding-L05-002', 'cricket', 'cricket-fielding', 'Fielding', 5, 'Team Fielding', 'Communication', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-fielding-L05-003', 'cricket', 'cricket-fielding', 'Fielding', 5, 'Pressure Runouts', 'Win the match', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-fielding-L05-004', 'cricket', 'cricket-fielding', 'Fielding', 5, 'Complete Fielder', 'All fielding skills', 12, 50, false, 'complete_any_in_category_level_4'),

-- Wicketkeeping
('cricket-wicketkeeping-L01-001', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 1, 'Stance', 'Ready position', 7, 30, true, 'none'),
('cricket-wicketkeeping-L01-002', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 1, 'Gathering', 'Clean takes', 7, 30, true, 'none'),
('cricket-wicketkeeping-L01-003', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 1, 'Leg Side Takes', 'Collect down leg', 7, 30, true, 'none'),
('cricket-wicketkeeping-L01-004', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 1, 'Off Side Takes', 'Wide collections', 7, 30, true, 'none'),
('cricket-wicketkeeping-L02-001', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 2, 'Standing Up', 'To the stumps', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-wicketkeeping-L02-002', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 2, 'Standing Back', 'Pace bowling', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-wicketkeeping-L02-003', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 2, 'Stumpings', 'Quick hands', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-wicketkeeping-L02-004', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 2, 'Diving Catches', 'Edge collection', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-wicketkeeping-L03-001', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 3, 'Spin Keeping', 'Track turn', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-wicketkeeping-L03-002', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 3, 'Leg Bye Prevention', 'Stay alert', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-wicketkeeping-L03-003', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 3, 'Run Out Attempts', 'Break stumps', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-wicketkeeping-L03-004', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 3, 'Communication', 'Lead the field', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-wicketkeeping-L04-001', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 4, 'Lightning Stumping', 'MS Dhoni speed', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-wicketkeeping-L04-002', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 4, 'High Takes', 'Above the stumps', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-wicketkeeping-L04-003', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 4, 'Long Session', 'Endurance keeping', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-wicketkeeping-L04-004', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 4, 'Match Awareness', 'Game situations', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-wicketkeeping-L05-001', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 5, 'Gilchrist Takes', 'World class keeping', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-wicketkeeping-L05-002', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 5, 'Complete Keeper', 'All conditions', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-wicketkeeping-L05-003', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 5, 'Keeping to All Types', 'Pace and spin', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-wicketkeeping-L05-004', 'cricket', 'cricket-wicketkeeping', 'Wicketkeeping', 5, 'Keeper-Batsman', 'Contribute with bat', 12, 50, false, 'complete_any_in_category_level_4'),

-- Running Between Wickets
('cricket-running-L01-001', 'cricket', 'cricket-running', 'Running Between Wickets', 1, 'Calling', 'Yes, No, Wait', 7, 30, true, 'none'),
('cricket-running-L01-002', 'cricket', 'cricket-running', 'Running Between Wickets', 1, 'Grounding Bat', 'Cross the line', 7, 30, true, 'none'),
('cricket-running-L01-003', 'cricket', 'cricket-running', 'Running Between Wickets', 1, 'Quick Singles', 'Rotate strike', 7, 30, true, 'none'),
('cricket-running-L01-004', 'cricket', 'cricket-running', 'Running Between Wickets', 1, 'Turn and Run', 'Efficient turning', 7, 30, true, 'none'),
('cricket-running-L02-001', 'cricket', 'cricket-running', 'Running Between Wickets', 2, 'Easy Twos', 'Quick running', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-running-L02-002', 'cricket', 'cricket-running', 'Running Between Wickets', 2, 'Backing Up', 'Non-striker ready', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-running-L02-003', 'cricket', 'cricket-running', 'Running Between Wickets', 2, 'Reading Fielders', 'Know arm strength', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-running-L02-004', 'cricket', 'cricket-running', 'Running Between Wickets', 2, 'Third Run', 'Push for three', 8, 35, false, 'complete_any_in_category_level_1'),
('cricket-running-L03-001', 'cricket', 'cricket-running', 'Running Between Wickets', 3, 'Strike Rotation', 'Farm strike smartly', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-running-L03-002', 'cricket', 'cricket-running', 'Running Between Wickets', 3, 'Risky Singles', 'When to gamble', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-running-L03-003', 'cricket', 'cricket-running', 'Running Between Wickets', 3, 'Overthrow Runs', 'Extra runs', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-running-L03-004', 'cricket', 'cricket-running', 'Running Between Wickets', 3, 'Partnership Running', 'Build understanding', 9, 40, false, 'complete_any_in_category_level_2'),
('cricket-running-L04-001', 'cricket', 'cricket-running', 'Running Between Wickets', 4, 'Pressure Running', 'Death overs', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-running-L04-002', 'cricket', 'cricket-running', 'Running Between Wickets', 4, 'Sacrifice Run', 'Give up wicket for runs', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-running-L04-003', 'cricket', 'cricket-running', 'Running Between Wickets', 4, 'Run Chase', 'Score under pressure', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-running-L04-004', 'cricket', 'cricket-running', 'Running Between Wickets', 4, 'Field Placement Read', 'Gaps for runs', 10, 45, false, 'complete_any_in_category_level_3'),
('cricket-running-L05-001', 'cricket', 'cricket-running', 'Running Between Wickets', 5, 'Elite Running', 'Match-winning runs', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-running-L05-002', 'cricket', 'cricket-running', 'Running Between Wickets', 5, 'Fitness Running', 'Run hard all day', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-running-L05-003', 'cricket', 'cricket-running', 'Running Between Wickets', 5, 'Smart Running', 'Decision making', 12, 50, false, 'complete_any_in_category_level_4'),
('cricket-running-L05-004', 'cricket', 'cricket-running', 'Running Between Wickets', 5, 'Complete Runner', 'All situations', 12, 50, false, 'complete_any_in_category_level_4')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description;