-- Insert 100 Table Tennis drills (5 categories x 20 drills each)
INSERT INTO drills (id, sport, category, category_name, title, description, level, duration_minutes, xp, free, solo_or_duo, unlock_requires) VALUES
-- Forehand (20 drills)
('tt-fh-1-1', 'table-tennis', 'tt-forehand', 'Forehand', 'Basic Forehand Drive', 'Learn the fundamental forehand stroke', 1, 8, 25, true, 'solo', 'none'),
('tt-fh-1-2', 'table-tennis', 'tt-forehand', 'Forehand', 'Grip and Stance', 'Proper shake-hand or pen-hold grip', 1, 8, 25, true, 'solo', 'none'),
('tt-fh-1-3', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Block', 'Block incoming shots', 1, 10, 30, true, 'solo', 'none'),
('tt-fh-1-4', 'table-tennis', 'tt-forehand', 'Forehand', 'Crosscourt Forehand', 'Direct shots crosscourt', 1, 7, 20, true, 'duo', 'none'),
('tt-fh-2-1', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Topspin', 'Add topspin to forehand', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-fh-2-2', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Smash', 'Put away high balls', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-fh-2-3', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Loop', 'Learn the loop technique', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('tt-fh-2-4', 'table-tennis', 'tt-forehand', 'Forehand', 'Multi-ball Forehand', 'Fast forehand repetitions', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('tt-fh-3-1', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Counter Loop', 'Loop against loop', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fh-3-2', 'table-tennis', 'tt-forehand', 'Forehand', 'Wide Forehand Reach', 'Extend for wide balls', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fh-3-3', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Flick', 'Attack short balls', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fh-3-4', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Kill Shot', 'Finish points decisively', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fh-4-1', 'table-tennis', 'tt-forehand', 'Forehand', 'Power Loop Forehand', 'Maximum power loops', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('tt-fh-4-2', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Pivot', 'Pivot around backhand', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-fh-4-3', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Under Pressure', 'Execute under time pressure', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('tt-fh-4-4', 'table-tennis', 'tt-forehand', 'Forehand', 'Forehand Placement Drill', 'Target specific zones', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-fh-5-1', 'table-tennis', 'tt-forehand', 'Forehand', 'Elite Forehand Loop', 'Pro level forehand attacks', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-fh-5-2', 'table-tennis', 'tt-forehand', 'Forehand', 'Match Point Forehand', 'Pressure forehand execution', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-fh-5-3', 'table-tennis', 'tt-forehand', 'Forehand', 'All Table Forehand', 'Cover entire table with forehand', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('tt-fh-5-4', 'table-tennis', 'tt-forehand', 'Forehand', 'Complete Forehand Mastery', 'Full forehand assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Backhand (20 drills)
('tt-bh-1-1', 'table-tennis', 'tt-backhand', 'Backhand', 'Basic Backhand Drive', 'Learn the fundamental backhand', 1, 8, 25, true, 'solo', 'none'),
('tt-bh-1-2', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Block', 'Block fast incoming shots', 1, 8, 25, true, 'solo', 'none'),
('tt-bh-1-3', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Ready Position', 'Proper backhand stance', 1, 10, 30, true, 'solo', 'none'),
('tt-bh-1-4', 'table-tennis', 'tt-backhand', 'Backhand', 'Crosscourt Backhand', 'Direct shots crosscourt', 1, 7, 20, true, 'duo', 'none'),
('tt-bh-2-1', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Topspin', 'Add topspin to backhand', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-bh-2-2', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Push', 'Control with backspin push', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-bh-2-3', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Punch', 'Flat fast backhand', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('tt-bh-2-4', 'table-tennis', 'tt-backhand', 'Backhand', 'Multi-ball Backhand', 'Fast backhand repetitions', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('tt-bh-3-1', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Counter', 'Counter attack from backhand', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-bh-3-2', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Flick', 'Attack short balls', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-bh-3-3', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand to Backhand Rally', 'Extended backhand rallies', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-bh-3-4', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Open Up', 'Open rally with backhand', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-bh-4-1', 'table-tennis', 'tt-backhand', 'Backhand', 'Power Backhand Loop', 'Maximum power backhand', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('tt-bh-4-2', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Banana Flick', 'Curved flick technique', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-bh-4-3', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Kill', 'Winner from backhand side', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('tt-bh-4-4', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Placement', 'Target specific zones', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-bh-5-1', 'table-tennis', 'tt-backhand', 'Backhand', 'Elite Backhand Attack', 'Pro level backhand attacks', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-bh-5-2', 'table-tennis', 'tt-backhand', 'Backhand', 'Match Point Backhand', 'Pressure backhand execution', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-bh-5-3', 'table-tennis', 'tt-backhand', 'Backhand', 'Backhand Domination', 'Win points from backhand', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('tt-bh-5-4', 'table-tennis', 'tt-backhand', 'Backhand', 'Complete Backhand Mastery', 'Full backhand assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Serve (20 drills)
('tt-sv-1-1', 'table-tennis', 'tt-serve', 'Serve', 'Basic Backspin Serve', 'Learn the fundamental serve', 1, 8, 25, true, 'solo', 'none'),
('tt-sv-1-2', 'table-tennis', 'tt-serve', 'Serve', 'Topspin Serve Basics', 'Add topspin to serve', 1, 8, 25, true, 'solo', 'none'),
('tt-sv-1-3', 'table-tennis', 'tt-serve', 'Serve', 'Serve Placement', 'Target different zones', 1, 10, 30, true, 'solo', 'none'),
('tt-sv-1-4', 'table-tennis', 'tt-serve', 'Serve', 'Legal Serve Practice', 'Meet all serve rules', 1, 7, 20, true, 'solo', 'none'),
('tt-sv-2-1', 'table-tennis', 'tt-serve', 'Serve', 'Sidespin Serve', 'Add sidespin variation', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-sv-2-2', 'table-tennis', 'tt-serve', 'Serve', 'Short Serve Control', 'Keep serves short on table', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-sv-2-3', 'table-tennis', 'tt-serve', 'Serve', 'Long Fast Serve', 'Surprise with long serve', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('tt-sv-2-4', 'table-tennis', 'tt-serve', 'Serve', 'Serve and Third Ball', 'Plan attack after serve', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('tt-sv-3-1', 'table-tennis', 'tt-serve', 'Serve', 'Pendulum Serve', 'Master the pendulum motion', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('tt-sv-3-2', 'table-tennis', 'tt-serve', 'Serve', 'Reverse Pendulum', 'Opposite spin variation', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('tt-sv-3-3', 'table-tennis', 'tt-serve', 'Serve', 'Tomahawk Serve', 'High toss forehand serve', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('tt-sv-3-4', 'table-tennis', 'tt-serve', 'Serve', 'Serve Variation Pattern', 'Mix up serve types', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-sv-4-1', 'table-tennis', 'tt-serve', 'Serve', 'Ghost Serve', 'No spin fake serve', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('tt-sv-4-2', 'table-tennis', 'tt-serve', 'Serve', 'Heavy Backspin Serve', 'Maximum backspin serve', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('tt-sv-4-3', 'table-tennis', 'tt-serve', 'Serve', 'Serve Disguise', 'Hide serve type', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('tt-sv-4-4', 'table-tennis', 'tt-serve', 'Serve', 'Pressure Serve Routine', 'Serve under match pressure', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-sv-5-1', 'table-tennis', 'tt-serve', 'Serve', 'Elite Service Game', 'Pro level serving', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-sv-5-2', 'table-tennis', 'tt-serve', 'Serve', 'Ace Serve Pattern', 'Win points directly on serve', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-sv-5-3', 'table-tennis', 'tt-serve', 'Serve', 'Complete Serve Arsenal', 'All serve types mastered', 5, 22, 75, false, 'solo', 'complete_any_in_category_level_4'),
('tt-sv-5-4', 'table-tennis', 'tt-serve', 'Serve', 'Serve Mastery Test', 'Full serve assessment', 5, 25, 80, false, 'solo', 'complete_any_in_category_level_4'),

-- Footwork (20 drills)
('tt-fw-1-1', 'table-tennis', 'tt-footwork', 'Footwork', 'Basic Ready Stance', 'Proper table tennis stance', 1, 8, 25, true, 'solo', 'none'),
('tt-fw-1-2', 'table-tennis', 'tt-footwork', 'Footwork', 'Side to Side Movement', 'Move along the table', 1, 8, 25, true, 'solo', 'none'),
('tt-fw-1-3', 'table-tennis', 'tt-footwork', 'Footwork', 'Small Step Adjustment', 'Micro position adjustments', 1, 10, 30, true, 'solo', 'none'),
('tt-fw-1-4', 'table-tennis', 'tt-footwork', 'Footwork', 'Recovery Step', 'Return to ready position', 1, 7, 20, true, 'solo', 'none'),
('tt-fw-2-1', 'table-tennis', 'tt-footwork', 'Footwork', 'Two Step Pattern', 'Cover table in two steps', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-fw-2-2', 'table-tennis', 'tt-footwork', 'Footwork', 'Cross Step Movement', 'Cross step for wide balls', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('tt-fw-2-3', 'table-tennis', 'tt-footwork', 'Footwork', 'Forward and Back', 'Move in and out from table', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('tt-fw-2-4', 'table-tennis', 'tt-footwork', 'Footwork', 'Shadow Footwork', 'Practice without ball', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('tt-fw-3-1', 'table-tennis', 'tt-footwork', 'Footwork', 'Falkenberg Drill', 'Classic footwork pattern', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fw-3-2', 'table-tennis', 'tt-footwork', 'Footwork', 'Pivot Footwork', 'Pivot around backhand', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fw-3-3', 'table-tennis', 'tt-footwork', 'Footwork', 'Wide Ball Coverage', 'Reach extreme angles', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fw-3-4', 'table-tennis', 'tt-footwork', 'Footwork', 'One One Two Pattern', 'Alternating footwork pattern', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-fw-4-1', 'table-tennis', 'tt-footwork', 'Footwork', 'Speed Footwork Drill', 'Maximum speed movement', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('tt-fw-4-2', 'table-tennis', 'tt-footwork', 'Footwork', 'Irregular Footwork', 'Random ball placement', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-fw-4-3', 'table-tennis', 'tt-footwork', 'Footwork', 'Footwork Under Fatigue', 'Move when tired', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('tt-fw-4-4', 'table-tennis', 'tt-footwork', 'Footwork', 'Multi-ball Footwork', 'Rapid footwork with feeding', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-fw-5-1', 'table-tennis', 'tt-footwork', 'Footwork', 'Elite Movement Pattern', 'Pro level footwork', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-fw-5-2', 'table-tennis', 'tt-footwork', 'Footwork', 'Match Simulation Footwork', 'Game realistic movement', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-fw-5-3', 'table-tennis', 'tt-footwork', 'Footwork', 'All Table Coverage', 'Cover any ball on table', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('tt-fw-5-4', 'table-tennis', 'tt-footwork', 'Footwork', 'Complete Footwork Mastery', 'Full footwork assessment', 5, 25, 80, false, 'solo', 'complete_any_in_category_level_4'),

-- Tactics (20 drills)
('tt-tc-1-1', 'table-tennis', 'tt-tactics', 'Tactics', 'Basic Point Pattern', 'Simple rally patterns', 1, 8, 25, true, 'duo', 'none'),
('tt-tc-1-2', 'table-tennis', 'tt-tactics', 'Tactics', 'Reading Spin', 'Identify incoming spin', 1, 8, 25, true, 'duo', 'none'),
('tt-tc-1-3', 'table-tennis', 'tt-tactics', 'Tactics', 'Shot Selection Basics', 'Choose appropriate shots', 1, 10, 30, true, 'duo', 'none'),
('tt-tc-1-4', 'table-tennis', 'tt-tactics', 'Tactics', 'Rally Building', 'Construct points patiently', 1, 7, 20, true, 'duo', 'none'),
('tt-tc-2-1', 'table-tennis', 'tt-tactics', 'Tactics', 'Third Ball Attack', 'Attack after serve', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('tt-tc-2-2', 'table-tennis', 'tt-tactics', 'Tactics', 'Fourth Ball Pattern', 'Attack on receive', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('tt-tc-2-3', 'table-tennis', 'tt-tactics', 'Tactics', 'Placement over Power', 'Win with placement', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('tt-tc-2-4', 'table-tennis', 'tt-tactics', 'Tactics', 'Change of Pace', 'Vary ball speed', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('tt-tc-3-1', 'table-tennis', 'tt-tactics', 'Tactics', 'Opponent Analysis', 'Find weaknesses', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-tc-3-2', 'table-tennis', 'tt-tactics', 'Tactics', 'Defensive to Offensive', 'Transition play', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-tc-3-3', 'table-tennis', 'tt-tactics', 'Tactics', 'Middle Target Attack', 'Exploit the middle zone', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('tt-tc-3-4', 'table-tennis', 'tt-tactics', 'Tactics', 'Spin Variation Pattern', 'Mix spins strategically', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('tt-tc-4-1', 'table-tennis', 'tt-tactics', 'Tactics', 'Advanced Pattern Play', 'Complex rally patterns', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('tt-tc-4-2', 'table-tennis', 'tt-tactics', 'Tactics', 'Match Momentum', 'Control match flow', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-tc-4-3', 'table-tennis', 'tt-tactics', 'Tactics', 'Comeback Strategy', 'Recover from behind', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('tt-tc-4-4', 'table-tennis', 'tt-tactics', 'Tactics', 'Playing Styles Counter', 'Beat different styles', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('tt-tc-5-1', 'table-tennis', 'tt-tactics', 'Tactics', 'Elite Tactical Thinking', 'Pro level strategy', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-tc-5-2', 'table-tennis', 'tt-tactics', 'Tactics', 'Match Simulation', 'Full match tactics', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('tt-tc-5-3', 'table-tennis', 'tt-tactics', 'Tactics', 'Championship Points', 'Handle pressure points', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('tt-tc-5-4', 'table-tennis', 'tt-tactics', 'Tactics', 'Complete Tactical Mastery', 'Full tactics assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4');