-- Insert 100 Rugby drills (5 categories x 20 drills each)
INSERT INTO drills (id, sport, category, category_name, title, description, level, duration_minutes, xp, free, solo_or_duo, unlock_requires) VALUES
-- Passing (20 drills)
('rugby-ps-1-1', 'rugby', 'rugby-passing', 'Passing', 'Basic Lateral Pass', 'Learn the fundamental lateral pass', 1, 8, 25, true, 'duo', 'none'),
('rugby-ps-1-2', 'rugby', 'rugby-passing', 'Passing', 'Two Hand Grip', 'Master proper ball handling', 1, 8, 25, true, 'solo', 'none'),
('rugby-ps-1-3', 'rugby', 'rugby-passing', 'Passing', 'Stationary Pass Drill', 'Pass accurately while stationary', 1, 10, 30, true, 'duo', 'none'),
('rugby-ps-1-4', 'rugby', 'rugby-passing', 'Passing', 'Short Pop Pass', 'Execute short distance pops', 1, 7, 20, true, 'duo', 'none'),
('rugby-ps-2-1', 'rugby', 'rugby-passing', 'Passing', 'Running Pass', 'Pass while moving at pace', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ps-2-2', 'rugby', 'rugby-passing', 'Passing', 'Skip Pass Introduction', 'Miss one player with pass', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ps-2-3', 'rugby', 'rugby-passing', 'Passing', 'Pass Under Pressure', 'Execute pass with defender closing', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ps-2-4', 'rugby', 'rugby-passing', 'Passing', 'Spin Pass Basics', 'Learn the spiral pass technique', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ps-3-1', 'rugby', 'rugby-passing', 'Passing', 'Long Spin Pass', 'Distance spiral passing', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ps-3-2', 'rugby', 'rugby-passing', 'Passing', 'Offload Technique', 'Pass in contact', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ps-3-3', 'rugby', 'rugby-passing', 'Passing', 'One Hand Offload', 'Single arm offload drill', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ps-3-4', 'rugby', 'rugby-passing', 'Passing', 'Reverse Pass', 'Behind the back pass', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ps-4-1', 'rugby', 'rugby-passing', 'Passing', 'Contact Offload Chain', 'Multiple offloads in sequence', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ps-4-2', 'rugby', 'rugby-passing', 'Passing', 'Ground Pop Pass', 'Pop pass from the floor', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ps-4-3', 'rugby', 'rugby-passing', 'Passing', 'Blindside Skip', 'Skip pass to blindside wing', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ps-4-4', 'rugby', 'rugby-passing', 'Passing', 'Flick Pass Under Tackle', 'Execute pass while going down', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ps-5-1', 'rugby', 'rugby-passing', 'Passing', 'No Look Pass', 'Pass without looking at target', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-ps-5-2', 'rugby', 'rugby-passing', 'Passing', 'Match Speed Passing', 'Full speed pass sequences', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-ps-5-3', 'rugby', 'rugby-passing', 'Passing', 'Pressure Chain Passing', 'Team passing under pressure', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-ps-5-4', 'rugby', 'rugby-passing', 'Passing', 'Complete Passing Mastery', 'Full passing assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Tackling (20 drills)
('rugby-tk-1-1', 'rugby', 'rugby-tackling', 'Tackling', 'Tackle Technique Basics', 'Learn safe tackle fundamentals', 1, 8, 25, true, 'duo', 'none'),
('rugby-tk-1-2', 'rugby', 'rugby-tackling', 'Tackling', 'Body Position Drill', 'Low body tackle stance', 1, 8, 25, true, 'solo', 'none'),
('rugby-tk-1-3', 'rugby', 'rugby-tackling', 'Tackling', 'Shield Tackle Practice', 'Tackle on pad holders', 1, 10, 30, true, 'duo', 'none'),
('rugby-tk-1-4', 'rugby', 'rugby-tackling', 'Tackling', 'Arm Wrap Technique', 'Wrap and secure tackle', 1, 7, 20, true, 'duo', 'none'),
('rugby-tk-2-1', 'rugby', 'rugby-tackling', 'Tackling', 'Side On Tackle', 'Tackle from the side', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-tk-2-2', 'rugby', 'rugby-tackling', 'Tackling', 'Front On Tackle', 'Head-on tackle technique', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-tk-2-3', 'rugby', 'rugby-tackling', 'Tackling', 'Rear Tackle Chase', 'Tackle from behind', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-tk-2-4', 'rugby', 'rugby-tackling', 'Tackling', 'Low Chop Tackle', 'Below knee tackle', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-tk-3-1', 'rugby', 'rugby-tackling', 'Tackling', 'Double Team Tackle', 'Two player tackle technique', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-tk-3-2', 'rugby', 'rugby-tackling', 'Tackling', 'Tackle and Turnover', 'Win ball after tackle', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-tk-3-3', 'rugby', 'rugby-tackling', 'Tackling', 'Drift Defense Tackle', 'Tackle in drift pattern', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-tk-3-4', 'rugby', 'rugby-tackling', 'Tackling', 'Scramble Defense', 'Recovery tackle technique', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-tk-4-1', 'rugby', 'rugby-tackling', 'Tackling', 'Dominant Tackle', 'Drive tackle backwards', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-tk-4-2', 'rugby', 'rugby-tackling', 'Tackling', 'Tackle in Traffic', 'Tackle in crowded space', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-tk-4-3', 'rugby', 'rugby-tackling', 'Tackling', 'Tackle Decision Making', 'Choose tackle type quickly', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-tk-4-4', 'rugby', 'rugby-tackling', 'Tackling', 'Tackle Fatigue Drill', 'Multiple tackles when tired', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-tk-5-1', 'rugby', 'rugby-tackling', 'Tackling', 'Elite Tackle Technique', 'Perfect tackle execution', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-tk-5-2', 'rugby', 'rugby-tackling', 'Tackling', 'Game Situation Tackles', 'Match realistic tackling', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-tk-5-3', 'rugby', 'rugby-tackling', 'Tackling', 'Tackle and Jackal', 'Compete for ball post tackle', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-tk-5-4', 'rugby', 'rugby-tackling', 'Tackling', 'Complete Tackle Mastery', 'Full tackle assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Kicking (20 drills)
('rugby-ki-1-1', 'rugby', 'rugby-kicking', 'Kicking', 'Drop Punt Basics', 'Learn the basic punt kick', 1, 8, 25, true, 'solo', 'none'),
('rugby-ki-1-2', 'rugby', 'rugby-kicking', 'Kicking', 'Ball Drop Technique', 'Perfect ball presentation', 1, 8, 25, true, 'solo', 'none'),
('rugby-ki-1-3', 'rugby', 'rugby-kicking', 'Kicking', 'Follow Through Drill', 'Proper kicking follow through', 1, 10, 30, true, 'solo', 'none'),
('rugby-ki-1-4', 'rugby', 'rugby-kicking', 'Kicking', 'Short Kick Practice', 'Accurate short kicks', 1, 7, 20, true, 'solo', 'none'),
('rugby-ki-2-1', 'rugby', 'rugby-kicking', 'Kicking', 'Box Kick Introduction', 'Scrum half box kick', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('rugby-ki-2-2', 'rugby', 'rugby-kicking', 'Kicking', 'Spiral Bomb Kick', 'High contestable kick', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('rugby-ki-2-3', 'rugby', 'rugby-kicking', 'Kicking', 'Grubber Kick', 'Low rolling kick', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('rugby-ki-2-4', 'rugby', 'rugby-kicking', 'Kicking', 'Touch Finder Kick', 'Kick to gain territory', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('rugby-ki-3-1', 'rugby', 'rugby-kicking', 'Kicking', 'Cross Field Kick', 'Kick across the field', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ki-3-2', 'rugby', 'rugby-kicking', 'Kicking', 'Chip and Chase', 'Kick over defender and recover', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ki-3-3', 'rugby', 'rugby-kicking', 'Kicking', 'Restart Kicks', 'Kickoff and restart technique', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ki-3-4', 'rugby', 'rugby-kicking', 'Kicking', 'Drop Goal Basics', 'Drop goal technique', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ki-4-1', 'rugby', 'rugby-kicking', 'Kicking', 'Place Kick Accuracy', 'Accurate goal kicking', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ki-4-2', 'rugby', 'rugby-kicking', 'Kicking', 'Pressure Kick Drill', 'Kick under match pressure', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ki-4-3', 'rugby', 'rugby-kicking', 'Kicking', 'Long Range Goal', 'Extended distance kicks', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ki-4-4', 'rugby', 'rugby-kicking', 'Kicking', 'Wind Adjustment Kick', 'Kick in windy conditions', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ki-5-1', 'rugby', 'rugby-kicking', 'Kicking', 'Elite Place Kicking', 'Pro level goal kicking', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('rugby-ki-5-2', 'rugby', 'rugby-kicking', 'Kicking', 'Match Situation Kicking', 'Kicks in game scenarios', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('rugby-ki-5-3', 'rugby', 'rugby-kicking', 'Kicking', 'All Kicks Challenge', 'Execute all kick types', 5, 22, 75, false, 'solo', 'complete_any_in_category_level_4'),
('rugby-ki-5-4', 'rugby', 'rugby-kicking', 'Kicking', 'Complete Kicking Mastery', 'Full kicking assessment', 5, 25, 80, false, 'solo', 'complete_any_in_category_level_4'),

-- Rucking (20 drills)
('rugby-ru-1-1', 'rugby', 'rugby-rucking', 'Rucking', 'Ruck Body Position', 'Low driving stance', 1, 8, 25, true, 'duo', 'none'),
('rugby-ru-1-2', 'rugby', 'rugby-rucking', 'Rucking', 'Binding Technique', 'Proper ruck binding', 1, 8, 25, true, 'duo', 'none'),
('rugby-ru-1-3', 'rugby', 'rugby-rucking', 'Rucking', 'Clearing Out Basics', 'Remove defender from ruck', 1, 10, 30, true, 'duo', 'none'),
('rugby-ru-1-4', 'rugby', 'rugby-rucking', 'Rucking', 'Ball Placement', 'Present ball correctly', 1, 7, 20, true, 'duo', 'none'),
('rugby-ru-2-1', 'rugby', 'rugby-rucking', 'Rucking', 'First Cleaner Speed', 'Fast first to ruck', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ru-2-2', 'rugby', 'rugby-rucking', 'Rucking', 'Counter Ruck Defense', 'Defend the ruck', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ru-2-3', 'rugby', 'rugby-rucking', 'Rucking', 'Quick Ball Securing', 'Fast ball from ruck', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ru-2-4', 'rugby', 'rugby-rucking', 'Rucking', 'Ruck Entry Angles', 'Enter ruck legally', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ru-3-1', 'rugby', 'rugby-rucking', 'Rucking', 'Jackal Technique', 'Compete for turnover', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ru-3-2', 'rugby', 'rugby-rucking', 'Rucking', 'Double Clear Out', 'Two player ruck clear', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ru-3-3', 'rugby', 'rugby-rucking', 'Rucking', 'Ruck Decision Making', 'When to ruck or not', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ru-3-4', 'rugby', 'rugby-rucking', 'Rucking', 'Pod Formation Ruck', 'Work in attacking pods', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('rugby-ru-4-1', 'rugby', 'rugby-rucking', 'Rucking', 'Ruck Steal Under Pressure', 'Win ball in contested ruck', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ru-4-2', 'rugby', 'rugby-rucking', 'Rucking', 'Fast Ruck Tempo', 'Increase ruck speed', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ru-4-3', 'rugby', 'rugby-rucking', 'Rucking', 'Ruck and Reset', 'Continuous ruck phases', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ru-4-4', 'rugby', 'rugby-rucking', 'Rucking', 'Fatigue Ruck Drill', 'Ruck when exhausted', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('rugby-ru-5-1', 'rugby', 'rugby-rucking', 'Rucking', 'Elite Ruck Technique', 'Pro level ruck skills', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-ru-5-2', 'rugby', 'rugby-rucking', 'Rucking', 'Multi Phase Rucking', 'Extended ruck sequences', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-ru-5-3', 'rugby', 'rugby-rucking', 'Rucking', 'Game Ruck Simulation', 'Match realistic rucking', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('rugby-ru-5-4', 'rugby', 'rugby-rucking', 'Rucking', 'Complete Ruck Mastery', 'Full ruck assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Fitness (20 drills)
('rugby-ft-1-1', 'rugby', 'rugby-fitness', 'Fitness', 'Rugby Sprint Basics', 'Short explosive sprints', 1, 8, 25, true, 'solo', 'none'),
('rugby-ft-1-2', 'rugby', 'rugby-fitness', 'Fitness', 'Agility Ladder', 'Footwork drills', 1, 8, 25, true, 'solo', 'none'),
('rugby-ft-1-3', 'rugby', 'rugby-fitness', 'Fitness', 'Basic Conditioning', 'Cardio foundation', 1, 10, 30, true, 'solo', 'none'),
('rugby-ft-1-4', 'rugby', 'rugby-fitness', 'Fitness', 'Core Strength Start', 'Basic core exercises', 1, 7, 20, true, 'solo', 'none'),
('rugby-ft-2-1', 'rugby', 'rugby-fitness', 'Fitness', 'Shuttle Runs', 'Change of direction speed', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('rugby-ft-2-2', 'rugby', 'rugby-fitness', 'Fitness', 'Power Training', 'Explosive power drills', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('rugby-ft-2-3', 'rugby', 'rugby-fitness', 'Fitness', 'Interval Training', 'High intensity intervals', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('rugby-ft-2-4', 'rugby', 'rugby-fitness', 'Fitness', 'Contact Conditioning', 'Fitness with contact', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('rugby-ft-3-1', 'rugby', 'rugby-fitness', 'Fitness', 'Bronco Test Prep', 'Bronco fitness test training', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ft-3-2', 'rugby', 'rugby-fitness', 'Fitness', 'Game Simulation Fitness', 'Match intensity training', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ft-3-3', 'rugby', 'rugby-fitness', 'Fitness', 'Recovery Runs', 'Active recovery training', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ft-3-4', 'rugby', 'rugby-fitness', 'Fitness', 'Strength Endurance', 'Sustained power output', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('rugby-ft-4-1', 'rugby', 'rugby-fitness', 'Fitness', 'Elite Cardio', 'Advanced cardiovascular', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ft-4-2', 'rugby', 'rugby-fitness', 'Fitness', 'Repeated Effort Training', 'Multiple high intensity efforts', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ft-4-3', 'rugby', 'rugby-fitness', 'Fitness', 'Position Specific Fitness', 'Training for your position', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ft-4-4', 'rugby', 'rugby-fitness', 'Fitness', 'Pre Season Conditioning', 'Intensive fitness block', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('rugby-ft-5-1', 'rugby', 'rugby-fitness', 'Fitness', 'Pro Level Fitness', 'Elite rugby conditioning', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('rugby-ft-5-2', 'rugby', 'rugby-fitness', 'Fitness', 'Mental Toughness Fitness', 'Train through fatigue', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('rugby-ft-5-3', 'rugby', 'rugby-fitness', 'Fitness', 'Peak Performance Training', 'Maximize fitness levels', 5, 22, 75, false, 'solo', 'complete_any_in_category_level_4'),
('rugby-ft-5-4', 'rugby', 'rugby-fitness', 'Fitness', 'Complete Fitness Mastery', 'Full fitness assessment', 5, 25, 80, false, 'solo', 'complete_any_in_category_level_4');