-- Insert 100 Baseball drills (5 categories x 20 drills each)
INSERT INTO drills (id, sport, category, category_name, title, description, level, duration_minutes, xp, free, solo_or_duo, unlock_requires) VALUES
-- Hitting (20 drills)
('bb-ht-1-1', 'baseball', 'baseball-hitting', 'Hitting', 'Batting Stance Basics', 'Learn the fundamental batting stance', 1, 8, 25, true, 'solo', 'none'),
('bb-ht-1-2', 'baseball', 'baseball-hitting', 'Hitting', 'Grip and Load', 'Proper bat grip and load position', 1, 8, 25, true, 'solo', 'none'),
('bb-ht-1-3', 'baseball', 'baseball-hitting', 'Hitting', 'Tee Work Basics', 'Hit off a batting tee', 1, 10, 30, true, 'solo', 'none'),
('bb-ht-1-4', 'baseball', 'baseball-hitting', 'Hitting', 'Swing Path Drill', 'Develop level swing path', 1, 7, 20, true, 'solo', 'none'),
('bb-ht-2-1', 'baseball', 'baseball-hitting', 'Hitting', 'Soft Toss Hitting', 'Hit soft tossed balls', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ht-2-2', 'baseball', 'baseball-hitting', 'Hitting', 'Front Toss Drill', 'Hit from front tosser', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ht-2-3', 'baseball', 'baseball-hitting', 'Hitting', 'Inside Pitch Hitting', 'Turn on inside pitches', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ht-2-4', 'baseball', 'baseball-hitting', 'Hitting', 'Outside Pitch Hitting', 'Drive outside pitches', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ht-3-1', 'baseball', 'baseball-hitting', 'Hitting', 'Live Batting Practice', 'Face live pitching', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ht-3-2', 'baseball', 'baseball-hitting', 'Hitting', 'Opposite Field Hitting', 'Hit to opposite field', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ht-3-3', 'baseball', 'baseball-hitting', 'Hitting', 'Breaking Ball Recognition', 'Identify breaking balls', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ht-3-4', 'baseball', 'baseball-hitting', 'Hitting', 'Two Strike Approach', 'Choke up and make contact', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ht-4-1', 'baseball', 'baseball-hitting', 'Hitting', 'Power Hitting Drill', 'Generate maximum power', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-ht-4-2', 'baseball', 'baseball-hitting', 'Hitting', 'Situational Hitting', 'Execute in different counts', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-ht-4-3', 'baseball', 'baseball-hitting', 'Hitting', 'Velocity Training', 'Handle high velocity pitches', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-ht-4-4', 'baseball', 'baseball-hitting', 'Hitting', 'Pitch Selection', 'Swing at strikes only', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-ht-5-1', 'baseball', 'baseball-hitting', 'Hitting', 'Elite Hitting Approach', 'Pro level at-bat quality', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-ht-5-2', 'baseball', 'baseball-hitting', 'Hitting', 'Game Situation Hitting', 'Execute in pressure spots', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-ht-5-3', 'baseball', 'baseball-hitting', 'Hitting', 'All Pitch Types', 'Handle any pitch thrown', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('bb-ht-5-4', 'baseball', 'baseball-hitting', 'Hitting', 'Complete Hitting Mastery', 'Full hitting assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Pitching (20 drills)
('bb-pt-1-1', 'baseball', 'baseball-pitching', 'Pitching', 'Pitching Mechanics Start', 'Basic throwing motion', 1, 8, 25, true, 'solo', 'none'),
('bb-pt-1-2', 'baseball', 'baseball-pitching', 'Pitching', 'Fastball Grip', 'Four seam and two seam grips', 1, 8, 25, true, 'solo', 'none'),
('bb-pt-1-3', 'baseball', 'baseball-pitching', 'Pitching', 'Balance Point Drill', 'Proper leg lift balance', 1, 10, 30, true, 'solo', 'none'),
('bb-pt-1-4', 'baseball', 'baseball-pitching', 'Pitching', 'Follow Through', 'Complete the throwing motion', 1, 7, 20, true, 'solo', 'none'),
('bb-pt-2-1', 'baseball', 'baseball-pitching', 'Pitching', 'Target Practice', 'Hit specific locations', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-pt-2-2', 'baseball', 'baseball-pitching', 'Pitching', 'Changeup Introduction', 'Learn the changeup grip', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('bb-pt-2-3', 'baseball', 'baseball-pitching', 'Pitching', 'Curveball Basics', 'Learn curve grip and spin', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('bb-pt-2-4', 'baseball', 'baseball-pitching', 'Pitching', 'Long Toss Program', 'Build arm strength', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-pt-3-1', 'baseball', 'baseball-pitching', 'Pitching', 'Slider Development', 'Learn the slider pitch', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('bb-pt-3-2', 'baseball', 'baseball-pitching', 'Pitching', 'Pitch Sequencing', 'Set up batters strategically', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-pt-3-3', 'baseball', 'baseball-pitching', 'Pitching', 'Holding Runners', 'Control the running game', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-pt-3-4', 'baseball', 'baseball-pitching', 'Pitching', 'Pitch Tunneling', 'Make pitches look the same', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-pt-4-1', 'baseball', 'baseball-pitching', 'Pitching', 'Velocity Training', 'Increase pitch speed', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('bb-pt-4-2', 'baseball', 'baseball-pitching', 'Pitching', 'Command Work', 'Precision location training', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-pt-4-3', 'baseball', 'baseball-pitching', 'Pitching', 'Pitch Mix Strategy', 'Use full arsenal effectively', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-pt-4-4', 'baseball', 'baseball-pitching', 'Pitching', 'Pressure Pitching', 'Pitch in tough situations', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-pt-5-1', 'baseball', 'baseball-pitching', 'Pitching', 'Elite Pitch Arsenal', 'Pro level pitch variety', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-pt-5-2', 'baseball', 'baseball-pitching', 'Pitching', 'Complete Game Stamina', 'Pitch deep into games', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('bb-pt-5-3', 'baseball', 'baseball-pitching', 'Pitching', 'Shutdown Innings', 'Dominate key situations', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('bb-pt-5-4', 'baseball', 'baseball-pitching', 'Pitching', 'Complete Pitching Mastery', 'Full pitching assessment', 5, 25, 80, false, 'solo', 'complete_any_in_category_level_4'),

-- Fielding (20 drills)
('bb-fd-1-1', 'baseball', 'baseball-fielding', 'Fielding', 'Ready Position', 'Athletic fielding stance', 1, 8, 25, true, 'solo', 'none'),
('bb-fd-1-2', 'baseball', 'baseball-fielding', 'Fielding', 'Ground Ball Basics', 'Field grounders properly', 1, 8, 25, true, 'solo', 'none'),
('bb-fd-1-3', 'baseball', 'baseball-fielding', 'Fielding', 'Fly Ball Tracking', 'Track and catch fly balls', 1, 10, 30, true, 'solo', 'none'),
('bb-fd-1-4', 'baseball', 'baseball-fielding', 'Fielding', 'Throwing Mechanics', 'Accurate throws to bases', 1, 7, 20, true, 'duo', 'none'),
('bb-fd-2-1', 'baseball', 'baseball-fielding', 'Fielding', 'Backhand Play', 'Field balls to glove side', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-fd-2-2', 'baseball', 'baseball-fielding', 'Fielding', 'Forehand Play', 'Field balls to throwing side', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-fd-2-3', 'baseball', 'baseball-fielding', 'Fielding', 'Charging Bunts', 'Field bunts aggressively', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-fd-2-4', 'baseball', 'baseball-fielding', 'Fielding', 'Double Play Footwork', 'Turn double plays', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-fd-3-1', 'baseball', 'baseball-fielding', 'Fielding', 'Diving Catch Drill', 'Extend range with dives', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-fd-3-2', 'baseball', 'baseball-fielding', 'Fielding', 'Outfield Wall Work', 'Play balls at the wall', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('bb-fd-3-3', 'baseball', 'baseball-fielding', 'Fielding', 'Relay Throws', 'Hit the cutoff man', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-fd-3-4', 'baseball', 'baseball-fielding', 'Fielding', 'Tag Play Technique', 'Apply tags effectively', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-fd-4-1', 'baseball', 'baseball-fielding', 'Fielding', 'Slow Roller Play', 'Bare hand slow grounders', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-fd-4-2', 'baseball', 'baseball-fielding', 'Fielding', 'Communication Drill', 'Call for fly balls properly', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-fd-4-3', 'baseball', 'baseball-fielding', 'Fielding', 'Quick Release Throws', 'Speed up transfer', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-fd-4-4', 'baseball', 'baseball-fielding', 'Fielding', 'Bad Hop Drill', 'Handle tricky bounces', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-fd-5-1', 'baseball', 'baseball-fielding', 'Fielding', 'Elite Range Drill', 'Maximize fielding range', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-fd-5-2', 'baseball', 'baseball-fielding', 'Fielding', 'Web Gems Practice', 'Highlight reel plays', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-fd-5-3', 'baseball', 'baseball-fielding', 'Fielding', 'Position Versatility', 'Play multiple positions', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('bb-fd-5-4', 'baseball', 'baseball-fielding', 'Fielding', 'Complete Fielding Mastery', 'Full fielding assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Base Running (20 drills)
('bb-br-1-1', 'baseball', 'baseball-baserunning', 'Base Running', 'First Step Quickness', 'Explosive first step out of box', 1, 8, 25, true, 'solo', 'none'),
('bb-br-1-2', 'baseball', 'baseball-baserunning', 'Base Running', 'Running Through First', 'Sprint through the bag', 1, 8, 25, true, 'solo', 'none'),
('bb-br-1-3', 'baseball', 'baseball-baserunning', 'Base Running', 'Rounding Bases', 'Proper base path curves', 1, 10, 30, true, 'solo', 'none'),
('bb-br-1-4', 'baseball', 'baseball-baserunning', 'Base Running', 'Base Stealing Basics', 'Read the pitcher for steals', 1, 7, 20, true, 'solo', 'none'),
('bb-br-2-1', 'baseball', 'baseball-baserunning', 'Base Running', 'Lead Off Technique', 'Safe primary leads', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-br-2-2', 'baseball', 'baseball-baserunning', 'Base Running', 'Secondary Lead', 'Read ball off bat', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-br-2-3', 'baseball', 'baseball-baserunning', 'Base Running', 'Delayed Steal', 'Steal on catcher throw back', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-br-2-4', 'baseball', 'baseball-baserunning', 'Base Running', 'Tagging Up', 'Score on sacrifice flies', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-br-3-1', 'baseball', 'baseball-baserunning', 'Base Running', 'Hit and Run Execution', 'Execute hit and run play', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-br-3-2', 'baseball', 'baseball-baserunning', 'Base Running', 'Reading Ball in Dirt', 'Advance on wild pitches', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-br-3-3', 'baseball', 'baseball-baserunning', 'Base Running', 'First to Third', 'Take extra base on singles', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-br-3-4', 'baseball', 'baseball-baserunning', 'Base Running', 'Scoring from Second', 'Read outfield positioning', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-br-4-1', 'baseball', 'baseball-baserunning', 'Base Running', 'Straight Steal', 'Pure speed steals', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-br-4-2', 'baseball', 'baseball-baserunning', 'Base Running', 'Reading Outfielders', 'Judge outfield arm strength', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-br-4-3', 'baseball', 'baseball-baserunning', 'Base Running', 'Sliding Technique', 'Perfect slide timing', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('bb-br-4-4', 'baseball', 'baseball-baserunning', 'Base Running', 'Rundown Escape', 'Get out of pickle plays', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-br-5-1', 'baseball', 'baseball-baserunning', 'Base Running', 'Elite Steal Rate', 'Pro level base stealing', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-br-5-2', 'baseball', 'baseball-baserunning', 'Base Running', 'Aggressive Baserunning', 'Take calculated risks', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-br-5-3', 'baseball', 'baseball-baserunning', 'Base Running', 'Game Situation Running', 'Execute in all scenarios', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('bb-br-5-4', 'baseball', 'baseball-baserunning', 'Base Running', 'Complete Baserunning Mastery', 'Full baserunning assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Catching (20 drills)
('bb-ct-1-1', 'baseball', 'baseball-catching', 'Catching', 'Crouch Position', 'Proper catching stance', 1, 8, 25, true, 'solo', 'none'),
('bb-ct-1-2', 'baseball', 'baseball-catching', 'Catching', 'Receiving Basics', 'Catch and frame pitches', 1, 8, 25, true, 'duo', 'none'),
('bb-ct-1-3', 'baseball', 'baseball-catching', 'Catching', 'Blocking Balls', 'Block pitches in dirt', 1, 10, 30, true, 'duo', 'none'),
('bb-ct-1-4', 'baseball', 'baseball-catching', 'Catching', 'Throwing to Second', 'Pop time to second base', 1, 7, 20, true, 'duo', 'none'),
('bb-ct-2-1', 'baseball', 'baseball-catching', 'Catching', 'Framing Technique', 'Make close pitches look like strikes', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ct-2-2', 'baseball', 'baseball-catching', 'Catching', 'Lateral Blocking', 'Block pitches to sides', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ct-2-3', 'baseball', 'baseball-catching', 'Catching', 'Throwing to Third', 'Quick release to third', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ct-2-4', 'baseball', 'baseball-catching', 'Catching', 'Popup Footwork', 'Catch foul popups', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('bb-ct-3-1', 'baseball', 'baseball-catching', 'Catching', 'Pitch Calling Basics', 'Call game strategically', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ct-3-2', 'baseball', 'baseball-catching', 'Catching', 'Holding Runners', 'Control running game', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ct-3-3', 'baseball', 'baseball-catching', 'Catching', 'Tag Play at Plate', 'Block and tag at home', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ct-3-4', 'baseball', 'baseball-catching', 'Catching', 'Communication Leadership', 'Direct the infield', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('bb-ct-4-1', 'baseball', 'baseball-catching', 'Catching', 'Elite Framing', 'Maximize strike calls', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-ct-4-2', 'baseball', 'baseball-catching', 'Catching', 'Quick Pop Time', 'Sub 2.0 throws to second', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('bb-ct-4-3', 'baseball', 'baseball-catching', 'Catching', 'Pitcher Management', 'Get best from pitchers', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('bb-ct-4-4', 'baseball', 'baseball-catching', 'Catching', 'Game Endurance', 'Stay fresh late in games', 4, 18, 60, false, 'solo', 'complete_any_in_category_level_3'),
('bb-ct-5-1', 'baseball', 'baseball-catching', 'Catching', 'Pro Receiving', 'Elite level receiving', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-ct-5-2', 'baseball', 'baseball-catching', 'Catching', 'Complete Game Calling', 'Master pitch sequencing', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('bb-ct-5-3', 'baseball', 'baseball-catching', 'Catching', 'Defensive QB', 'Lead team defensively', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('bb-ct-5-4', 'baseball', 'baseball-catching', 'Catching', 'Complete Catching Mastery', 'Full catching assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4');