-- Insert 100 American Football drills (5 categories x 20 drills each)
INSERT INTO drills (id, sport, category, category_name, title, description, level, duration_minutes, xp, free, solo_or_duo, unlock_requires) VALUES
-- Throwing (20 drills)
('af-th-1-1', 'american-football', 'af-throwing', 'Throwing', 'Basic Grip and Release', 'Learn proper football grip', 1, 8, 25, true, 'solo', 'none'),
('af-th-1-2', 'american-football', 'af-throwing', 'Throwing', 'Stance and Footwork', 'QB stance fundamentals', 1, 8, 25, true, 'solo', 'none'),
('af-th-1-3', 'american-football', 'af-throwing', 'Throwing', 'Short Pass Accuracy', 'Accurate short throws', 1, 10, 30, true, 'duo', 'none'),
('af-th-1-4', 'american-football', 'af-throwing', 'Throwing', 'Follow Through Drill', 'Complete throwing motion', 1, 7, 20, true, 'solo', 'none'),
('af-th-2-1', 'american-football', 'af-throwing', 'Throwing', 'Out Route Timing', 'Hit out routes on time', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-th-2-2', 'american-football', 'af-throwing', 'Throwing', 'Slant Pass Accuracy', 'Quick slant throws', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-th-2-3', 'american-football', 'af-throwing', 'Throwing', 'Rollout Passing', 'Throw on the move', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-th-2-4', 'american-football', 'af-throwing', 'Throwing', 'Deep Ball Basics', 'Long range passes', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-th-3-1', 'american-football', 'af-throwing', 'Throwing', 'Touch Pass Drill', 'Vary ball trajectory', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-th-3-2', 'american-football', 'af-throwing', 'Throwing', 'Pocket Awareness', 'Step up in pocket', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-th-3-3', 'american-football', 'af-throwing', 'Throwing', 'Back Shoulder Throw', 'Placement away from DB', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-th-3-4', 'american-football', 'af-throwing', 'Throwing', 'Red Zone Passing', 'Compressed field throws', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-th-4-1', 'american-football', 'af-throwing', 'Throwing', 'Seam Route Accuracy', 'Thread the seam', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-th-4-2', 'american-football', 'af-throwing', 'Throwing', 'Pressure Throwing', 'Throw under duress', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-th-4-3', 'american-football', 'af-throwing', 'Throwing', 'Play Action Pass', 'Sell the fake', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-th-4-4', 'american-football', 'af-throwing', 'Throwing', 'Two Minute Drill', 'Clock management throws', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-th-5-1', 'american-football', 'af-throwing', 'Throwing', 'Elite Deep Ball', 'Pro level deep throws', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-th-5-2', 'american-football', 'af-throwing', 'Throwing', 'All Route Accuracy', 'Hit every route type', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-th-5-3', 'american-football', 'af-throwing', 'Throwing', 'Game Situation Passing', 'Execute in all scenarios', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('af-th-5-4', 'american-football', 'af-throwing', 'Throwing', 'Complete Throwing Mastery', 'Full throwing assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Catching (20 drills)
('af-ct-1-1', 'american-football', 'af-catching', 'Catching', 'Basic Catch Technique', 'Hands position for catches', 1, 8, 25, true, 'solo', 'none'),
('af-ct-1-2', 'american-football', 'af-catching', 'Catching', 'Eye Discipline', 'Track ball into hands', 1, 8, 25, true, 'duo', 'none'),
('af-ct-1-3', 'american-football', 'af-catching', 'Catching', 'Short Route Catches', 'Quick passing game', 1, 10, 30, true, 'duo', 'none'),
('af-ct-1-4', 'american-football', 'af-catching', 'Catching', 'Tuck and Secure', 'Secure the football', 1, 7, 20, true, 'duo', 'none'),
('af-ct-2-1', 'american-football', 'af-catching', 'Catching', 'Over Shoulder Catch', 'Catch deep balls', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-ct-2-2', 'american-football', 'af-catching', 'Catching', 'Sideline Toe Drag', 'Stay in bounds', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-ct-2-3', 'american-football', 'af-catching', 'Catching', 'Contested Catch', 'Win against coverage', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-ct-2-4', 'american-football', 'af-catching', 'Catching', 'Route Running Intro', 'Basic route tree', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-ct-3-1', 'american-football', 'af-catching', 'Catching', 'One Hand Catch', 'Extend range with one hand', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-ct-3-2', 'american-football', 'af-catching', 'Catching', 'Back Shoulder Reception', 'Adjust to back shoulder', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-ct-3-3', 'american-football', 'af-catching', 'Catching', 'RAC Drill', 'Run after catch', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-ct-3-4', 'american-football', 'af-catching', 'Catching', 'Jump Ball Technique', 'Win 50/50 balls', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-ct-4-1', 'american-football', 'af-catching', 'Catching', 'Traffic Catches', 'Catch in crowds', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-ct-4-2', 'american-football', 'af-catching', 'Catching', 'Route Precision', 'Exact route breaks', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-ct-4-3', 'american-football', 'af-catching', 'Catching', 'End Zone Focus', 'Red zone catches', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-ct-4-4', 'american-football', 'af-catching', 'Catching', 'High Point Catch', 'Attack the ball at peak', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-ct-5-1', 'american-football', 'af-catching', 'Catching', 'Elite Route Running', 'Pro level routes', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-ct-5-2', 'american-football', 'af-catching', 'Catching', 'Spectacular Catch', 'Highlight reel catches', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-ct-5-3', 'american-football', 'af-catching', 'Catching', 'Complete Route Tree', 'All routes mastered', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('af-ct-5-4', 'american-football', 'af-catching', 'Catching', 'Complete Catching Mastery', 'Full catching assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Running (20 drills)
('af-rn-1-1', 'american-football', 'af-running', 'Running', 'Ball Security Basics', 'Protect the football', 1, 8, 25, true, 'solo', 'none'),
('af-rn-1-2', 'american-football', 'af-running', 'Running', 'Stance and Start', 'Explosive first step', 1, 8, 25, true, 'solo', 'none'),
('af-rn-1-3', 'american-football', 'af-running', 'Running', 'Follow the Blocks', 'Read blocking', 1, 10, 30, true, 'duo', 'none'),
('af-rn-1-4', 'american-football', 'af-running', 'Running', 'Handoff Drill', 'Secure handoffs', 1, 7, 20, true, 'duo', 'none'),
('af-rn-2-1', 'american-football', 'af-running', 'Running', 'Cut Back Running', 'Find the cutback lane', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-rn-2-2', 'american-football', 'af-running', 'Running', 'Power Running', 'Run through contact', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-rn-2-3', 'american-football', 'af-running', 'Running', 'Outside Zone', 'Stretch the defense', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-rn-2-4', 'american-football', 'af-running', 'Running', 'Pass Protection', 'Block in pass game', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-rn-3-1', 'american-football', 'af-running', 'Running', 'Vision Training', 'Read holes quickly', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-rn-3-2', 'american-football', 'af-running', 'Running', 'Stiff Arm Technique', 'Fend off tacklers', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-rn-3-3', 'american-football', 'af-running', 'Running', 'Screen Pass Running', 'Execute screen plays', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-rn-3-4', 'american-football', 'af-running', 'Running', 'Goal Line Power', 'Short yardage running', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-rn-4-1', 'american-football', 'af-running', 'Running', 'Broken Tackle Drill', 'Break tackles consistently', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-rn-4-2', 'american-football', 'af-running', 'Running', 'Receiving Back', 'Catch out of backfield', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-rn-4-3', 'american-football', 'af-running', 'Running', 'One Cut Running', 'Decisive cut and go', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-rn-4-4', 'american-football', 'af-running', 'Running', 'Blitz Pickup', 'Recognize and block blitz', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-rn-5-1', 'american-football', 'af-running', 'Running', 'Elite Vision', 'Pro level hole reading', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-rn-5-2', 'american-football', 'af-running', 'Running', 'Complete Back Skills', 'All RB skills combined', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-rn-5-3', 'american-football', 'af-running', 'Running', 'Game Situation Running', 'Execute in all scenarios', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('af-rn-5-4', 'american-football', 'af-running', 'Running', 'Complete Running Mastery', 'Full running assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Defense (20 drills)
('af-df-1-1', 'american-football', 'af-defense', 'Defense', 'Tackle Form Basics', 'Proper tackling technique', 1, 8, 25, true, 'duo', 'none'),
('af-df-1-2', 'american-football', 'af-defense', 'Defense', 'Defensive Stance', 'Athletic ready position', 1, 8, 25, true, 'solo', 'none'),
('af-df-1-3', 'american-football', 'af-defense', 'Defense', 'Pursuit Angles', 'Take proper angles', 1, 10, 30, true, 'duo', 'none'),
('af-df-1-4', 'american-football', 'af-defense', 'Defense', 'Shed Blocks', 'Get off blocks', 1, 7, 20, true, 'duo', 'none'),
('af-df-2-1', 'american-football', 'af-defense', 'Defense', 'Pass Coverage Basics', 'Cover receivers', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-df-2-2', 'american-football', 'af-defense', 'Defense', 'Zone Coverage', 'Play zone defense', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-df-2-3', 'american-football', 'af-defense', 'Defense', 'Man Coverage', 'Tight man to man', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-df-2-4', 'american-football', 'af-defense', 'Defense', 'Run Fit Drill', 'Fill your gap', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-df-3-1', 'american-football', 'af-defense', 'Defense', 'Ball Hawking', 'Create turnovers', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-df-3-2', 'american-football', 'af-defense', 'Defense', 'Blitz Technique', 'Rush the passer', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-df-3-3', 'american-football', 'af-defense', 'Defense', 'Press Coverage', 'Jam at the line', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-df-3-4', 'american-football', 'af-defense', 'Defense', 'Deep Coverage', 'Prevent big plays', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-df-4-1', 'american-football', 'af-defense', 'Defense', 'Pass Rush Moves', 'Beat offensive linemen', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-df-4-2', 'american-football', 'af-defense', 'Defense', 'Play Recognition', 'Diagnose offense quickly', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-df-4-3', 'american-football', 'af-defense', 'Defense', 'Interception Drill', 'Catch like a receiver', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-df-4-4', 'american-football', 'af-defense', 'Defense', 'Combo Blitz', 'Coordinate with teammates', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-df-5-1', 'american-football', 'af-defense', 'Defense', 'Elite Coverage Skills', 'Pro level coverage', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-df-5-2', 'american-football', 'af-defense', 'Defense', 'Game Changer Plays', 'Create momentum shifts', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-df-5-3', 'american-football', 'af-defense', 'Defense', 'Complete Defender', 'All defense skills', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('af-df-5-4', 'american-football', 'af-defense', 'Defense', 'Complete Defense Mastery', 'Full defense assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Special Teams (20 drills)
('af-st-1-1', 'american-football', 'af-special-teams', 'Special Teams', 'Kickoff Coverage', 'Cover kicks downfield', 1, 8, 25, true, 'duo', 'none'),
('af-st-1-2', 'american-football', 'af-special-teams', 'Special Teams', 'Punt Coverage', 'Cover punts', 1, 8, 25, true, 'duo', 'none'),
('af-st-1-3', 'american-football', 'af-special-teams', 'Special Teams', 'Return Basics', 'Field kicks safely', 1, 10, 30, true, 'duo', 'none'),
('af-st-1-4', 'american-football', 'af-special-teams', 'Special Teams', 'Kick Blocking', 'Block kicks safely', 1, 7, 20, true, 'duo', 'none'),
('af-st-2-1', 'american-football', 'af-special-teams', 'Special Teams', 'Kickoff Return', 'Return for yardage', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-st-2-2', 'american-football', 'af-special-teams', 'Special Teams', 'Punt Return', 'Return punts safely', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('af-st-2-3', 'american-football', 'af-special-teams', 'Special Teams', 'Gunner Drill', 'Beat double team', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-st-2-4', 'american-football', 'af-special-teams', 'Special Teams', 'Field Goal Block', 'Scheme to block FGs', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('af-st-3-1', 'american-football', 'af-special-teams', 'Special Teams', 'Onside Kick Recovery', 'Recover onside kicks', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-st-3-2', 'american-football', 'af-special-teams', 'Special Teams', 'Return Vision', 'Find running lanes', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-st-3-3', 'american-football', 'af-special-teams', 'Special Teams', 'Punt Formation', 'Protect the punter', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('af-st-3-4', 'american-football', 'af-special-teams', 'Special Teams', 'FG/PAT Hold', 'Perfect snap and hold', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('af-st-4-1', 'american-football', 'af-special-teams', 'Special Teams', 'Explosive Return', 'Set up big returns', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-st-4-2', 'american-football', 'af-special-teams', 'Special Teams', 'Coverage Speed', 'Get downfield fast', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-st-4-3', 'american-football', 'af-special-teams', 'Special Teams', 'Fake Punt/FG', 'Execute fakes', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('af-st-4-4', 'american-football', 'af-special-teams', 'Special Teams', 'Pressure Kicks', 'Block under pressure', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('af-st-5-1', 'american-football', 'af-special-teams', 'Special Teams', 'Game Changing Returns', 'Score on returns', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-st-5-2', 'american-football', 'af-special-teams', 'Special Teams', 'Elite Coverage', 'Pro level coverage', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('af-st-5-3', 'american-football', 'af-special-teams', 'Special Teams', 'Complete ST Player', 'All special teams skills', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('af-st-5-4', 'american-football', 'af-special-teams', 'Special Teams', 'Special Teams Mastery', 'Full ST assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4');