-- Insert 100 Field Hockey drills (5 categories x 20 drills each)
INSERT INTO drills (id, sport, category, category_name, title, description, level, duration_minutes, xp, free, solo_or_duo, unlock_requires) VALUES
-- Stickwork (20 drills)
('fh-sw-1-1', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Basic Grip', 'Learn proper stick grip', 1, 8, 25, true, 'solo', 'none'),
('fh-sw-1-2', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Forehand Push', 'Basic push pass technique', 1, 8, 25, true, 'solo', 'none'),
('fh-sw-1-3', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Receiving Basics', 'Stop and control ball', 1, 10, 30, true, 'solo', 'none'),
('fh-sw-1-4', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Ball Control Start', 'Keep ball close to stick', 1, 7, 20, true, 'solo', 'none'),
('fh-sw-2-1', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Slap Pass', 'Power slap passing', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('fh-sw-2-2', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Reverse Stick Control', 'Control on reverse side', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('fh-sw-2-3', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Aerial Ball Receive', 'Control aerial balls', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('fh-sw-2-4', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Quick Hands Drill', 'Fast stick manipulation', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('fh-sw-3-1', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Hit Technique', 'Powerful hitting', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('fh-sw-3-2', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Flick Basics', 'Lift ball over stick', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('fh-sw-3-3', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Tomahawk Pass', 'Reverse side power pass', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('fh-sw-3-4', 'field-hockey', 'fh-stickwork', 'Stickwork', 'One Touch Passing', 'First time passes', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-sw-4-1', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Drag Flick', 'Penalty corner specialist', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('fh-sw-4-2', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Aerial Pass', 'Long distance aerials', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-sw-4-3', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Reverse Hit', 'Power shot on reverse', 4, 15, 55, false, 'solo', 'complete_any_in_category_level_3'),
('fh-sw-4-4', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Pressure Ball Handling', 'Control under pressure', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-sw-5-1', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Elite Stick Skills', 'Pro level handling', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-sw-5-2', 'field-hockey', 'fh-stickwork', 'Stickwork', 'All Surface Control', 'Control in any condition', 5, 20, 70, false, 'solo', 'complete_any_in_category_level_4'),
('fh-sw-5-3', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Match Tempo Skills', 'Execute at game speed', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('fh-sw-5-4', 'field-hockey', 'fh-stickwork', 'Stickwork', 'Complete Stickwork Mastery', 'Full stickwork assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Dribbling (20 drills)
('fh-dr-1-1', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Basic Carry', 'Move with ball at pace', 1, 8, 25, true, 'solo', 'none'),
('fh-dr-1-2', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Close Control Walk', 'Slow speed control', 1, 8, 25, true, 'solo', 'none'),
('fh-dr-1-3', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Straight Line Speed', 'Fast straight dribbling', 1, 10, 30, true, 'solo', 'none'),
('fh-dr-1-4', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Cone Weave Start', 'Basic slalom dribbling', 1, 7, 20, true, 'solo', 'none'),
('fh-dr-2-1', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Indian Dribble', 'Ball manipulation technique', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('fh-dr-2-2', 'field-hockey', 'fh-dribbling', 'Dribbling', 'V Drag', 'Change direction quickly', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('fh-dr-2-3', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Speed Burst', 'Acceleration with ball', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('fh-dr-2-4', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Reverse Dribble', 'Use reverse stick', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('fh-dr-3-1', 'field-hockey', 'fh-dribbling', 'Dribbling', '3D Skills', 'Lift ball to beat player', 3, 12, 45, false, 'solo', 'complete_any_in_category_level_2'),
('fh-dr-3-2', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Elimination Move', 'Beat defender 1v1', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('fh-dr-3-3', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Dummy and Go', 'Fake pass and dribble', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('fh-dr-3-4', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Tight Space Dribble', 'Navigate crowded areas', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-dr-4-1', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Multiple Defender Beat', 'Dribble past 2+ players', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-dr-4-2', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Circle Entry', 'Enter circle with ball', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-dr-4-3', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Counter Attack Carry', 'Fast break dribbling', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-dr-4-4', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Pressure Dribble', 'Keep ball under pressure', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-dr-5-1', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Elite 1v1 Skills', 'Pro level elimination', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-dr-5-2', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Game Situation Dribble', 'Match realistic dribbling', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-dr-5-3', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Complete Ball Carrier', 'All dribbling skills', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('fh-dr-5-4', 'field-hockey', 'fh-dribbling', 'Dribbling', 'Dribbling Mastery Test', 'Full dribbling assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Shooting (20 drills)
('fh-sh-1-1', 'field-hockey', 'fh-shooting', 'Shooting', 'Basic Push Shot', 'Low shot on goal', 1, 8, 25, true, 'solo', 'none'),
('fh-sh-1-2', 'field-hockey', 'fh-shooting', 'Shooting', 'Slap Shot Basics', 'Power shot technique', 1, 8, 25, true, 'solo', 'none'),
('fh-sh-1-3', 'field-hockey', 'fh-shooting', 'Shooting', 'Stationary Shot', 'Shoot from set position', 1, 10, 30, true, 'solo', 'none'),
('fh-sh-1-4', 'field-hockey', 'fh-shooting', 'Shooting', 'Target Practice', 'Hit corners of goal', 1, 7, 20, true, 'solo', 'none'),
('fh-sh-2-1', 'field-hockey', 'fh-shooting', 'Shooting', 'Running Shot', 'Shoot while moving', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('fh-sh-2-2', 'field-hockey', 'fh-shooting', 'Shooting', 'Reverse Flick', 'Lifted shot on reverse', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('fh-sh-2-3', 'field-hockey', 'fh-shooting', 'Shooting', 'One Touch Finish', 'First time shooting', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('fh-sh-2-4', 'field-hockey', 'fh-shooting', 'Shooting', 'Circle Top Shot', 'Power from circle edge', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('fh-sh-3-1', 'field-hockey', 'fh-shooting', 'Shooting', 'Deflection Goals', 'Redirect passes', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-sh-3-2', 'field-hockey', 'fh-shooting', 'Shooting', 'Tomahawk Shot', 'Reverse power shot', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('fh-sh-3-3', 'field-hockey', 'fh-shooting', 'Shooting', 'Drag Flick Power', 'PC drag flick technique', 3, 15, 50, false, 'solo', 'complete_any_in_category_level_2'),
('fh-sh-3-4', 'field-hockey', 'fh-shooting', 'Shooting', 'Volley Finish', 'Strike aerial balls', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-sh-4-1', 'field-hockey', 'fh-shooting', 'Shooting', 'Pressure Shooting', 'Score under pressure', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-sh-4-2', 'field-hockey', 'fh-shooting', 'Shooting', 'Quick Release', 'Minimal backswing shot', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-sh-4-3', 'field-hockey', 'fh-shooting', 'Shooting', 'Goalkeeper Beat', 'Read and beat keeper', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-sh-4-4', 'field-hockey', 'fh-shooting', 'Shooting', 'Scramble Goals', 'Score in chaos', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-sh-5-1', 'field-hockey', 'fh-shooting', 'Shooting', 'Elite Finishing', 'Pro level shooting', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-sh-5-2', 'field-hockey', 'fh-shooting', 'Shooting', 'All Angle Goals', 'Score from anywhere', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-sh-5-3', 'field-hockey', 'fh-shooting', 'Shooting', 'Match Winner', 'Clutch shooting ability', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('fh-sh-5-4', 'field-hockey', 'fh-shooting', 'Shooting', 'Complete Shooting Mastery', 'Full shooting assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Defense (20 drills)
('fh-df-1-1', 'field-hockey', 'fh-defense', 'Defense', 'Defensive Stance', 'Athletic ready position', 1, 8, 25, true, 'solo', 'none'),
('fh-df-1-2', 'field-hockey', 'fh-defense', 'Defense', 'Jab Tackle', 'Basic tackle technique', 1, 8, 25, true, 'duo', 'none'),
('fh-df-1-3', 'field-hockey', 'fh-defense', 'Defense', 'Channeling', 'Force attacker direction', 1, 10, 30, true, 'duo', 'none'),
('fh-df-1-4', 'field-hockey', 'fh-defense', 'Defense', 'Recovery Run', 'Track back quickly', 1, 7, 20, true, 'solo', 'none'),
('fh-df-2-1', 'field-hockey', 'fh-defense', 'Defense', 'Block Tackle', 'Front-on tackle', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('fh-df-2-2', 'field-hockey', 'fh-defense', 'Defense', 'Marking Drill', 'Stay with your player', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('fh-df-2-3', 'field-hockey', 'fh-defense', 'Defense', 'Interception', 'Cut out passes', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('fh-df-2-4', 'field-hockey', 'fh-defense', 'Defense', 'Circle Defense', 'Defend in the D', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('fh-df-3-1', 'field-hockey', 'fh-defense', 'Defense', 'Shave Tackle', 'Dispossess from side', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-df-3-2', 'field-hockey', 'fh-defense', 'Defense', 'PC Defense', 'Penalty corner defending', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('fh-df-3-3', 'field-hockey', 'fh-defense', 'Defense', 'Double Team', 'Trap with teammate', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('fh-df-3-4', 'field-hockey', 'fh-defense', 'Defense', 'Clearance', 'Clear ball from danger', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-df-4-1', 'field-hockey', 'fh-defense', 'Defense', 'Aerial Defense', 'Handle high balls', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-df-4-2', 'field-hockey', 'fh-defense', 'Defense', 'Counter Defense', 'Defend fast breaks', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-df-4-3', 'field-hockey', 'fh-defense', 'Defense', 'Last Player Defense', 'One on one as last', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-df-4-4', 'field-hockey', 'fh-defense', 'Defense', 'Zonal Defense', 'Cover space not players', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-df-5-1', 'field-hockey', 'fh-defense', 'Defense', 'Elite Tackling', 'Pro level dispossession', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-df-5-2', 'field-hockey', 'fh-defense', 'Defense', 'Complete Defender', 'All defensive skills', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-df-5-3', 'field-hockey', 'fh-defense', 'Defense', 'Defensive Leader', 'Organize the defense', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('fh-df-5-4', 'field-hockey', 'fh-defense', 'Defense', 'Defense Mastery Test', 'Full defense assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4'),

-- Goalkeeping (20 drills)
('fh-gk-1-1', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Ready Stance', 'Athletic goalkeeper position', 1, 8, 25, true, 'solo', 'none'),
('fh-gk-1-2', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Basic Pad Save', 'Block with leg guards', 1, 8, 25, true, 'duo', 'none'),
('fh-gk-1-3', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Glove Save', 'Hand saves technique', 1, 10, 30, true, 'duo', 'none'),
('fh-gk-1-4', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Positioning Basics', 'Angle narrowing', 1, 7, 20, true, 'duo', 'none'),
('fh-gk-2-1', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Diving Save', 'Full extension dives', 2, 10, 35, false, 'duo', 'complete_any_in_category_level_1'),
('fh-gk-2-2', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Footwork Speed', 'Quick lateral movement', 2, 10, 35, false, 'solo', 'complete_any_in_category_level_1'),
('fh-gk-2-3', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'High Ball', 'Save lifted shots', 2, 12, 40, false, 'duo', 'complete_any_in_category_level_1'),
('fh-gk-2-4', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Recovery', 'Get up quickly after save', 2, 12, 40, false, 'solo', 'complete_any_in_category_level_1'),
('fh-gk-3-1', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'PC Saving', 'Penalty corner saves', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-gk-3-2', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', '1v1 Save', 'Save in one on one', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('fh-gk-3-3', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Clearing', 'Distribute after save', 3, 15, 50, false, 'duo', 'complete_any_in_category_level_2'),
('fh-gk-3-4', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Multiple Shots', 'Handle rebounds', 3, 12, 45, false, 'duo', 'complete_any_in_category_level_2'),
('fh-gk-4-1', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Drag Flick Save', 'Save powerful drag flicks', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-gk-4-2', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Aerial Ball', 'Deal with high balls', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-gk-4-3', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Communication', 'Direct the defense', 4, 15, 55, false, 'duo', 'complete_any_in_category_level_3'),
('fh-gk-4-4', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Reflex Saves', 'Close range reaction', 4, 18, 60, false, 'duo', 'complete_any_in_category_level_3'),
('fh-gk-5-1', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Elite Shot Stopping', 'Pro level saves', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-gk-5-2', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Match Simulation', 'Game realistic saves', 5, 20, 70, false, 'duo', 'complete_any_in_category_level_4'),
('fh-gk-5-3', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Complete Keeper', 'All goalkeeper skills', 5, 22, 75, false, 'duo', 'complete_any_in_category_level_4'),
('fh-gk-5-4', 'field-hockey', 'fh-goalkeeping', 'Goalkeeping', 'Goalkeeping Mastery', 'Full GK assessment', 5, 25, 80, false, 'duo', 'complete_any_in_category_level_4');