-- ============================================================
-- BASKETBALL DRILLS (100 total: 5 categories x 5 levels x 4 drills)
-- ============================================================

INSERT INTO public.drills (id, sport, category, category_name, level, title, description, duration_minutes, xp, free, unlock_requires) VALUES
-- Shooting
('basketball-shooting-L01-001', 'basketball', 'basketball-shooting', 'Shooting', 1, 'Basic Form', 'BEEF: Balance, Eyes, Elbow, Follow-through', 7, 30, true, 'none'),
('basketball-shooting-L01-002', 'basketball', 'basketball-shooting', 'Shooting', 1, 'Free Throws', 'Consistent free throw routine', 7, 30, true, 'none'),
('basketball-shooting-L01-003', 'basketball', 'basketball-shooting', 'Shooting', 1, 'Close Range', 'Shots within 5 feet', 7, 30, true, 'none'),
('basketball-shooting-L01-004', 'basketball', 'basketball-shooting', 'Shooting', 1, 'Layup Basics', 'Right and left hand layups', 7, 30, true, 'none'),
('basketball-shooting-L02-001', 'basketball', 'basketball-shooting', 'Shooting', 2, 'Mid Range', '10-15 foot jumpers', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-shooting-L02-002', 'basketball', 'basketball-shooting', 'Shooting', 2, 'Elbow Shots', 'Shoot from elbow spots', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-shooting-L02-003', 'basketball', 'basketball-shooting', 'Shooting', 2, 'Bank Shot', 'Use the backboard', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-shooting-L02-004', 'basketball', 'basketball-shooting', 'Shooting', 2, 'Spot Up Shooting', 'Catch and shoot', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-shooting-L03-001', 'basketball', 'basketball-shooting', 'Shooting', 3, 'Three Point Intro', 'Beyond the arc basics', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-shooting-L03-002', 'basketball', 'basketball-shooting', 'Shooting', 3, 'Off Screen', 'Curl and shoot', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-shooting-L03-003', 'basketball', 'basketball-shooting', 'Shooting', 3, 'Pull Up Jumper', 'Shoot off the dribble', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-shooting-L03-004', 'basketball', 'basketball-shooting', 'Shooting', 3, 'Floater', 'Soft touch in the lane', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-shooting-L04-001', 'basketball', 'basketball-shooting', 'Shooting', 4, 'Corner Three', 'Shortest 3-point shot', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-shooting-L04-002', 'basketball', 'basketball-shooting', 'Shooting', 4, 'Step Back', 'Create separation and shoot', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-shooting-L04-003', 'basketball', 'basketball-shooting', 'Shooting', 4, 'Contested Shots', 'Shoot with a hand in face', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-shooting-L04-004', 'basketball', 'basketball-shooting', 'Shooting', 4, 'Euro Step Finish', 'Change direction layup', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-shooting-L05-001', 'basketball', 'basketball-shooting', 'Shooting', 5, 'Curry Deep Range', 'Shoot from 28+ feet', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-shooting-L05-002', 'basketball', 'basketball-shooting', 'Shooting', 5, 'Game Winners', 'Pressure shot situations', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-shooting-L05-003', 'basketball', 'basketball-shooting', 'Shooting', 5, 'Quick Release', 'Minimize shot time', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-shooting-L05-004', 'basketball', 'basketball-shooting', 'Shooting', 5, 'Complete Scorer', 'All shot types mastery', 12, 50, false, 'complete_any_in_category_level_4'),

-- Dribbling
('basketball-dribbling-L01-001', 'basketball', 'basketball-dribbling', 'Dribbling', 1, 'Stationary Dribble', 'Control without moving', 7, 30, true, 'none'),
('basketball-dribbling-L01-002', 'basketball', 'basketball-dribbling', 'Dribbling', 1, 'Weak Hand', 'Non-dominant hand dribbling', 7, 30, true, 'none'),
('basketball-dribbling-L01-003', 'basketball', 'basketball-dribbling', 'Dribbling', 1, 'Eyes Up', 'Dribble without looking', 7, 30, true, 'none'),
('basketball-dribbling-L01-004', 'basketball', 'basketball-dribbling', 'Dribbling', 1, 'Walking Dribble', 'Move while dribbling', 7, 30, true, 'none'),
('basketball-dribbling-L02-001', 'basketball', 'basketball-dribbling', 'Dribbling', 2, 'Crossover', 'Quick hand switch', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-dribbling-L02-002', 'basketball', 'basketball-dribbling', 'Dribbling', 2, 'Between Legs', 'Protect the ball', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-dribbling-L02-003', 'basketball', 'basketball-dribbling', 'Dribbling', 2, 'Behind Back', 'Reverse direction', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-dribbling-L02-004', 'basketball', 'basketball-dribbling', 'Dribbling', 2, 'Speed Dribble', 'Full court speed', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-dribbling-L03-001', 'basketball', 'basketball-dribbling', 'Dribbling', 3, 'Hesitation Move', 'Freeze the defender', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-dribbling-L03-002', 'basketball', 'basketball-dribbling', 'Dribbling', 3, 'In and Out', 'Fake crossover', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-dribbling-L03-003', 'basketball', 'basketball-dribbling', 'Dribbling', 3, 'Combo Moves', 'Chain moves together', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-dribbling-L03-004', 'basketball', 'basketball-dribbling', 'Dribbling', 3, 'Cone Weave', 'Navigate obstacles', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-dribbling-L04-001', 'basketball', 'basketball-dribbling', 'Dribbling', 4, 'Killer Crossover', 'Ankle-breaker setup', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-dribbling-L04-002', 'basketball', 'basketball-dribbling', 'Dribbling', 4, 'Spin Move', '360 with control', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-dribbling-L04-003', 'basketball', 'basketball-dribbling', 'Dribbling', 4, 'Change of Pace', 'Speed variation', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-dribbling-L04-004', 'basketball', 'basketball-dribbling', 'Dribbling', 4, 'Pressure Handles', 'Dribble vs defense', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-dribbling-L05-001', 'basketball', 'basketball-dribbling', 'Dribbling', 5, 'Kyrie Handles', 'Elite ball control', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-dribbling-L05-002', 'basketball', 'basketball-dribbling', 'Dribbling', 5, 'Attack Mode', 'Dribble into scoring', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-dribbling-L05-003', 'basketball', 'basketball-dribbling', 'Dribbling', 5, 'Double Team Escape', 'Beat two defenders', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-dribbling-L05-004', 'basketball', 'basketball-dribbling', 'Dribbling', 5, 'Game Speed Handles', 'Full game intensity', 12, 50, false, 'complete_any_in_category_level_4'),

-- Passing
('basketball-passing-L01-001', 'basketball', 'basketball-passing', 'Passing', 1, 'Chest Pass', 'Basic two-hand pass', 7, 30, true, 'none'),
('basketball-passing-L01-002', 'basketball', 'basketball-passing', 'Passing', 1, 'Bounce Pass', 'Pass on the floor', 7, 30, true, 'none'),
('basketball-passing-L01-003', 'basketball', 'basketball-passing', 'Passing', 1, 'Overhead Pass', 'Pass over defenders', 7, 30, true, 'none'),
('basketball-passing-L01-004', 'basketball', 'basketball-passing', 'Passing', 1, 'Target Practice', 'Hit your teammate chest', 7, 30, true, 'none'),
('basketball-passing-L02-001', 'basketball', 'basketball-passing', 'Passing', 2, 'One Hand Push', 'Quick release pass', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-passing-L02-002', 'basketball', 'basketball-passing', 'Passing', 2, 'Wrap Around', 'Pass around defender', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-passing-L02-003', 'basketball', 'basketball-passing', 'Passing', 2, 'Lead Pass', 'Pass ahead of teammate', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-passing-L02-004', 'basketball', 'basketball-passing', 'Passing', 2, 'Entry Pass', 'Get ball to post', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-passing-L03-001', 'basketball', 'basketball-passing', 'Passing', 3, 'Skip Pass', 'Cross-court pass', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-passing-L03-002', 'basketball', 'basketball-passing', 'Passing', 3, 'Pocket Pass', 'Thread the needle', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-passing-L03-003', 'basketball', 'basketball-passing', 'Passing', 3, 'Pass Fake', 'Fake and pass', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-passing-L03-004', 'basketball', 'basketball-passing', 'Passing', 3, 'Fast Break Pass', 'Outlet and advance', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-passing-L04-001', 'basketball', 'basketball-passing', 'Passing', 4, 'Behind Back Pass', 'Flashy accuracy', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-passing-L04-002', 'basketball', 'basketball-passing', 'Passing', 4, 'Alley Oop', 'Lob for finish', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-passing-L04-003', 'basketball', 'basketball-passing', 'Passing', 4, 'No Look Pass', 'Deception passing', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-passing-L04-004', 'basketball', 'basketball-passing', 'Passing', 4, 'Drive and Kick', 'Attack then pass', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-passing-L05-001', 'basketball', 'basketball-passing', 'Passing', 5, 'LeBron Court Vision', 'Elite playmaking', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-passing-L05-002', 'basketball', 'basketball-passing', 'Passing', 5, 'Full Court Outlet', 'Long pass accuracy', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-passing-L05-003', 'basketball', 'basketball-passing', 'Passing', 5, 'Pick and Roll Pass', 'Read the defense', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-passing-L05-004', 'basketball', 'basketball-passing', 'Passing', 5, 'Assist Machine', 'Complete passer', 12, 50, false, 'complete_any_in_category_level_4'),

-- Defense
('basketball-defense-L01-001', 'basketball', 'basketball-defense', 'Defense', 1, 'Defensive Stance', 'Low and balanced', 7, 30, true, 'none'),
('basketball-defense-L01-002', 'basketball', 'basketball-defense', 'Defense', 1, 'Slide Steps', 'Lateral movement', 7, 30, true, 'none'),
('basketball-defense-L01-003', 'basketball', 'basketball-defense', 'Defense', 1, 'Closeout', 'Contest without fouling', 7, 30, true, 'none'),
('basketball-defense-L01-004', 'basketball', 'basketball-defense', 'Defense', 1, 'Ball Pressure', 'Stay on the ball', 7, 30, true, 'none'),
('basketball-defense-L02-001', 'basketball', 'basketball-defense', 'Defense', 2, 'Help Defense', 'Rotate and recover', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-defense-L02-002', 'basketball', 'basketball-defense', 'Defense', 2, 'Box Out', 'Secure rebounds', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-defense-L02-003', 'basketball', 'basketball-defense', 'Defense', 2, 'Steal Attempts', 'Active hands', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-defense-L02-004', 'basketball', 'basketball-defense', 'Defense', 2, 'Deny Position', 'No easy catches', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-defense-L03-001', 'basketball', 'basketball-defense', 'Defense', 3, 'Shot Contest', 'Alter shots', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-defense-L03-002', 'basketball', 'basketball-defense', 'Defense', 3, 'Pick and Roll D', 'Hedge and recover', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-defense-L03-003', 'basketball', 'basketball-defense', 'Defense', 3, 'Transition Defense', 'Get back quick', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-defense-L03-004', 'basketball', 'basketball-defense', 'Defense', 3, 'Charge Taking', 'Draw offensive fouls', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-defense-L04-001', 'basketball', 'basketball-defense', 'Defense', 4, 'Shot Blocking', 'Protect the rim', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-defense-L04-002', 'basketball', 'basketball-defense', 'Defense', 4, 'Switch Everything', 'Versatile defense', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-defense-L04-003', 'basketball', 'basketball-defense', 'Defense', 4, 'Post Defense', 'Guard the paint', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-defense-L04-004', 'basketball', 'basketball-defense', 'Defense', 4, 'Anticipation', 'Read the offense', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-defense-L05-001', 'basketball', 'basketball-defense', 'Defense', 5, 'Lockdown Defender', 'Shut down stars', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-defense-L05-002', 'basketball', 'basketball-defense', 'Defense', 5, 'DPOY Drills', 'Elite defense', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-defense-L05-003', 'basketball', 'basketball-defense', 'Defense', 5, 'Team Defense', 'Communication', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-defense-L05-004', 'basketball', 'basketball-defense', 'Defense', 5, 'Complete Defender', 'All defensive skills', 12, 50, false, 'complete_any_in_category_level_4'),

-- Rebounding
('basketball-rebounding-L01-001', 'basketball', 'basketball-rebounding', 'Rebounding', 1, 'Box Out Basics', 'Seal your man', 7, 30, true, 'none'),
('basketball-rebounding-L01-002', 'basketball', 'basketball-rebounding', 'Rebounding', 1, 'Jump Timing', 'Time your leap', 7, 30, true, 'none'),
('basketball-rebounding-L01-003', 'basketball', 'basketball-rebounding', 'Rebounding', 1, 'Two Hand Grab', 'Secure the ball', 7, 30, true, 'none'),
('basketball-rebounding-L01-004', 'basketball', 'basketball-rebounding', 'Rebounding', 1, 'Outlet After Rebound', 'Quick outlet pass', 7, 30, true, 'none'),
('basketball-rebounding-L02-001', 'basketball', 'basketball-rebounding', 'Rebounding', 2, 'Offensive Boards', 'Second chance points', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-rebounding-L02-002', 'basketball', 'basketball-rebounding', 'Rebounding', 2, 'Defensive Boards', 'End opponent possession', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-rebounding-L02-003', 'basketball', 'basketball-rebounding', 'Rebounding', 2, 'Read the Rim', 'Predict ball bounce', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-rebounding-L02-004', 'basketball', 'basketball-rebounding', 'Rebounding', 2, 'Position Battle', 'Fight for position', 8, 35, false, 'complete_any_in_category_level_1'),
('basketball-rebounding-L03-001', 'basketball', 'basketball-rebounding', 'Rebounding', 3, 'Tip Drill', 'Keep ball alive', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-rebounding-L03-002', 'basketball', 'basketball-rebounding', 'Rebounding', 3, 'Putback Score', 'Score off rebound', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-rebounding-L03-003', 'basketball', 'basketball-rebounding', 'Rebounding', 3, 'High Point Catch', 'Catch at apex', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-rebounding-L03-004', 'basketball', 'basketball-rebounding', 'Rebounding', 3, 'Long Rebound', 'Track missed threes', 9, 40, false, 'complete_any_in_category_level_2'),
('basketball-rebounding-L04-001', 'basketball', 'basketball-rebounding', 'Rebounding', 4, 'Rodman Hustle', 'Relentless pursuit', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-rebounding-L04-002', 'basketball', 'basketball-rebounding', 'Rebounding', 4, 'Crash vs Stay', 'Decision making', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-rebounding-L04-003', 'basketball', 'basketball-rebounding', 'Rebounding', 4, 'Free Throw Rebound', 'FT rebounding position', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-rebounding-L04-004', 'basketball', 'basketball-rebounding', 'Rebounding', 4, 'Traffic Rebounds', 'Multiple bodies', 10, 45, false, 'complete_any_in_category_level_3'),
('basketball-rebounding-L05-001', 'basketball', 'basketball-rebounding', 'Rebounding', 5, 'Glass Cleaner', 'Dominate the boards', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-rebounding-L05-002', 'basketball', 'basketball-rebounding', 'Rebounding', 5, 'Undersized Rebound', 'Out-hustle bigger players', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-rebounding-L05-003', 'basketball', 'basketball-rebounding', 'Rebounding', 5, 'Start the Break', 'Rebound to fast break', 12, 50, false, 'complete_any_in_category_level_4'),
('basketball-rebounding-L05-004', 'basketball', 'basketball-rebounding', 'Rebounding', 5, 'Rebound Champion', 'Complete rebounding', 12, 50, false, 'complete_any_in_category_level_4')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description;