-- ============================================================
-- TENNIS DRILLS (100 total: 5 categories x 5 levels x 4 drills)
-- ============================================================

-- Forehand drills
INSERT INTO public.drills (id, sport, category, category_name, level, title, description, duration_minutes, xp, free, unlock_requires) VALUES
('tennis-forehand-L01-001', 'tennis', 'tennis-forehand', 'Forehand', 1, 'Basic Grip', 'Learn the eastern and semi-western grips', 7, 30, true, 'none'),
('tennis-forehand-L01-002', 'tennis', 'tennis-forehand', 'Forehand', 1, 'Ready Position', 'Athletic stance for quick movement', 7, 30, true, 'none'),
('tennis-forehand-L01-003', 'tennis', 'tennis-forehand', 'Forehand', 1, 'Simple Swing Path', 'Low to high motion basics', 7, 30, true, 'none'),
('tennis-forehand-L01-004', 'tennis', 'tennis-forehand', 'Forehand', 1, 'Contact Point', 'Hit in front of your body', 7, 30, true, 'none'),
('tennis-forehand-L02-001', 'tennis', 'tennis-forehand', 'Forehand', 2, 'Topspin Introduction', 'Brush up on the ball for spin', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-forehand-L02-002', 'tennis', 'tennis-forehand', 'Forehand', 2, 'Weight Transfer', 'Step into shots', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-forehand-L02-003', 'tennis', 'tennis-forehand', 'Forehand', 2, 'Cross Court Rally', 'Hit 10 in a row cross court', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-forehand-L02-004', 'tennis', 'tennis-forehand', 'Forehand', 2, 'Down the Line', 'Aim for the sideline', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-forehand-L03-001', 'tennis', 'tennis-forehand', 'Forehand', 3, 'Heavy Topspin', 'Loop the ball with spin', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-forehand-L03-002', 'tennis', 'tennis-forehand', 'Forehand', 3, 'Inside Out Forehand', 'Run around backhand', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-forehand-L03-003', 'tennis', 'tennis-forehand', 'Forehand', 3, 'Approach Shot', 'Move forward after hitting', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-forehand-L03-004', 'tennis', 'tennis-forehand', 'Forehand', 3, 'Short Ball Attack', 'Punish weak balls', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-forehand-L04-001', 'tennis', 'tennis-forehand', 'Forehand', 4, 'Flat Forehand Power', 'Drive through the ball', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-forehand-L04-002', 'tennis', 'tennis-forehand', 'Forehand', 4, 'On the Run', 'Wide ball recovery', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-forehand-L04-003', 'tennis', 'tennis-forehand', 'Forehand', 4, 'Defensive Lob', 'High deep balls under pressure', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-forehand-L04-004', 'tennis', 'tennis-forehand', 'Forehand', 4, 'Change of Direction', 'Wrong-foot opponent', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-forehand-L05-001', 'tennis', 'tennis-forehand', 'Forehand', 5, 'Federer Finish', 'High follow through mastery', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-forehand-L05-002', 'tennis', 'tennis-forehand', 'Forehand', 5, 'Match Point Drill', 'Pressure forehand winners', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-forehand-L05-003', 'tennis', 'tennis-forehand', 'Forehand', 5, 'Pattern Play', 'Construct points', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-forehand-L05-004', 'tennis', 'tennis-forehand', 'Forehand', 5, 'Tour Level Rally', 'Extended high-intensity drills', 12, 50, false, 'complete_any_in_category_level_4'),

-- Backhand drills
('tennis-backhand-L01-001', 'tennis', 'tennis-backhand', 'Backhand', 1, 'Two-Hand Grip', 'Proper two-handed backhand grip', 7, 30, true, 'none'),
('tennis-backhand-L01-002', 'tennis', 'tennis-backhand', 'Backhand', 1, 'One-Hand Basics', 'Single hand backhand intro', 7, 30, true, 'none'),
('tennis-backhand-L01-003', 'tennis', 'tennis-backhand', 'Backhand', 1, 'Unit Turn', 'Shoulder rotation prep', 7, 30, true, 'none'),
('tennis-backhand-L01-004', 'tennis', 'tennis-backhand', 'Backhand', 1, 'Contact Zone', 'Hit at waist height', 7, 30, true, 'none'),
('tennis-backhand-L02-001', 'tennis', 'tennis-backhand', 'Backhand', 2, 'Topspin Backhand', 'Brush for spin', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-backhand-L02-002', 'tennis', 'tennis-backhand', 'Backhand', 2, 'Cross Court BH', 'Rally cross court', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-backhand-L02-003', 'tennis', 'tennis-backhand', 'Backhand', 2, 'Slice Backhand Intro', 'Cut under the ball', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-backhand-L02-004', 'tennis', 'tennis-backhand', 'Backhand', 2, 'Low Balls', 'Bend knees for low shots', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-backhand-L03-001', 'tennis', 'tennis-backhand', 'Backhand', 3, 'Down the Line BH', 'Hit with precision', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-backhand-L03-002', 'tennis', 'tennis-backhand', 'Backhand', 3, 'Slice Approach', 'Low slice and come in', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-backhand-L03-003', 'tennis', 'tennis-backhand', 'Backhand', 3, 'High Backhand', 'Handle shoulder-height balls', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-backhand-L03-004', 'tennis', 'tennis-backhand', 'Backhand', 3, 'Return of Serve BH', 'Return to backhand side', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-backhand-L04-001', 'tennis', 'tennis-backhand', 'Backhand', 4, 'Backhand Winner', 'Go for clean winners', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-backhand-L04-002', 'tennis', 'tennis-backhand', 'Backhand', 4, 'Defensive Slice', 'Stay in the point', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-backhand-L04-003', 'tennis', 'tennis-backhand', 'Backhand', 4, 'Running Backhand', 'Wide ball recovery', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-backhand-L04-004', 'tennis', 'tennis-backhand', 'Backhand', 4, 'Drop Shot BH', 'Touch and finesse', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-backhand-L05-001', 'tennis', 'tennis-backhand', 'Backhand', 5, 'One Hand Power', 'Wawrinka-style power', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-backhand-L05-002', 'tennis', 'tennis-backhand', 'Backhand', 5, 'Pressure Passing', 'Pass approaching player', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-backhand-L05-003', 'tennis', 'tennis-backhand', 'Backhand', 5, 'Backhand Patterns', 'Build points from BH', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-backhand-L05-004', 'tennis', 'tennis-backhand', 'Backhand', 5, 'Match Situations', 'Game-style backhand', 12, 50, false, 'complete_any_in_category_level_4'),

-- Serve drills
('tennis-serve-L01-001', 'tennis', 'tennis-serve', 'Serve', 1, 'Serve Grip', 'Continental grip basics', 7, 30, true, 'none'),
('tennis-serve-L01-002', 'tennis', 'tennis-serve', 'Serve', 1, 'Ball Toss', 'Consistent toss placement', 7, 30, true, 'none'),
('tennis-serve-L01-003', 'tennis', 'tennis-serve', 'Serve', 1, 'Trophy Position', 'Coil for power', 7, 30, true, 'none'),
('tennis-serve-L01-004', 'tennis', 'tennis-serve', 'Serve', 1, 'Basic Flat Serve', 'Get it in the box', 7, 30, true, 'none'),
('tennis-serve-L02-001', 'tennis', 'tennis-serve', 'Serve', 2, 'First Serve Power', 'Add pace safely', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-serve-L02-002', 'tennis', 'tennis-serve', 'Serve', 2, 'Second Serve Safety', 'Reliable second serve', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-serve-L02-003', 'tennis', 'tennis-serve', 'Serve', 2, 'Slice Serve Intro', 'Curve ball out wide', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-serve-L02-004', 'tennis', 'tennis-serve', 'Serve', 2, 'Serve Targets', 'Hit the corners', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-serve-L03-001', 'tennis', 'tennis-serve', 'Serve', 3, 'Kick Serve', 'High bouncing spin', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-serve-L03-002', 'tennis', 'tennis-serve', 'Serve', 3, 'Body Serve', 'Jam the opponent', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-serve-L03-003', 'tennis', 'tennis-serve', 'Serve', 3, 'Serve Plus One', 'Follow your serve', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-serve-L03-004', 'tennis', 'tennis-serve', 'Serve', 3, 'Deuce vs Ad Court', 'Court-specific serves', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-serve-L04-001', 'tennis', 'tennis-serve', 'Serve', 4, 'Ace Drill', 'Go for aces', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-serve-L04-002', 'tennis', 'tennis-serve', 'Serve', 4, 'Variation Mix', 'Disguise your serve', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-serve-L04-003', 'tennis', 'tennis-serve', 'Serve', 4, 'Clutch Serving', 'Deuce and ad points', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-serve-L04-004', 'tennis', 'tennis-serve', 'Serve', 4, 'Serve Under Fatigue', 'Late-set serving', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-serve-L05-001', 'tennis', 'tennis-serve', 'Serve', 5, 'Isner Power Serve', 'Maximum pace', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-serve-L05-002', 'tennis', 'tennis-serve', 'Serve', 5, 'Match Breaker', 'Win crucial service games', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-serve-L05-003', 'tennis', 'tennis-serve', 'Serve', 5, 'Serve and Volley', 'Old school approach', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-serve-L05-004', 'tennis', 'tennis-serve', 'Serve', 5, 'Complete Server', 'All serve types mastery', 12, 50, false, 'complete_any_in_category_level_4'),

-- Volley drills
('tennis-volley-L01-001', 'tennis', 'tennis-volley', 'Volley', 1, 'Volley Grip', 'Continental at the net', 7, 30, true, 'none'),
('tennis-volley-L01-002', 'tennis', 'tennis-volley', 'Volley', 1, 'Ready Position Net', 'Split step timing', 7, 30, true, 'none'),
('tennis-volley-L01-003', 'tennis', 'tennis-volley', 'Volley', 1, 'Forehand Volley', 'Punch dont swing', 7, 30, true, 'none'),
('tennis-volley-L01-004', 'tennis', 'tennis-volley', 'Volley', 1, 'Backhand Volley', 'Firm wrist contact', 7, 30, true, 'none'),
('tennis-volley-L02-001', 'tennis', 'tennis-volley', 'Volley', 2, 'Low Volley', 'Bend and lift', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-volley-L02-002', 'tennis', 'tennis-volley', 'Volley', 2, 'High Volley', 'Attack high balls', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-volley-L02-003', 'tennis', 'tennis-volley', 'Volley', 2, 'Volley Placement', 'Hit to open court', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-volley-L02-004', 'tennis', 'tennis-volley', 'Volley', 2, 'Volley-Volley Rally', 'Quick exchanges', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-volley-L03-001', 'tennis', 'tennis-volley', 'Volley', 3, 'Drop Volley', 'Touch at the net', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-volley-L03-002', 'tennis', 'tennis-volley', 'Volley', 3, 'Swing Volley', 'Put away high floaters', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-volley-L03-003', 'tennis', 'tennis-volley', 'Volley', 3, 'Half Volley', 'Pick up short balls', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-volley-L03-004', 'tennis', 'tennis-volley', 'Volley', 3, 'Approach and Volley', 'Come in behind shot', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-volley-L04-001', 'tennis', 'tennis-volley', 'Volley', 4, 'Reflex Volley', 'React to pace', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-volley-L04-002', 'tennis', 'tennis-volley', 'Volley', 4, 'Passing Shot Defense', 'Cover the passing shot', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-volley-L04-003', 'tennis', 'tennis-volley', 'Volley', 4, 'Doubles Net Play', 'Poach and cover', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-volley-L04-004', 'tennis', 'tennis-volley', 'Volley', 4, 'Angled Volley', 'Sharp crosscourt put-away', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-volley-L05-001', 'tennis', 'tennis-volley', 'Volley', 5, 'McEnroe Touch', 'Finesse volleys', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-volley-L05-002', 'tennis', 'tennis-volley', 'Volley', 5, 'Net Domination', 'Control the net', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-volley-L05-003', 'tennis', 'tennis-volley', 'Volley', 5, 'Serve-Volley Master', 'Complete S&V game', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-volley-L05-004', 'tennis', 'tennis-volley', 'Volley', 5, 'Clutch Net Points', 'Win at the net', 12, 50, false, 'complete_any_in_category_level_4'),

-- Footwork drills
('tennis-footwork-L01-001', 'tennis', 'tennis-footwork', 'Footwork', 1, 'Split Step', 'Time your split', 7, 30, true, 'none'),
('tennis-footwork-L01-002', 'tennis', 'tennis-footwork', 'Footwork', 1, 'Side Shuffle', 'Lateral movement basics', 7, 30, true, 'none'),
('tennis-footwork-L01-003', 'tennis', 'tennis-footwork', 'Footwork', 1, 'Recovery Steps', 'Get back to center', 7, 30, true, 'none'),
('tennis-footwork-L01-004', 'tennis', 'tennis-footwork', 'Footwork', 1, 'Forward Movement', 'Attack the ball', 7, 30, true, 'none'),
('tennis-footwork-L02-001', 'tennis', 'tennis-footwork', 'Footwork', 2, 'Crossover Steps', 'Cover more ground', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-footwork-L02-002', 'tennis', 'tennis-footwork', 'Footwork', 2, 'Wide Ball Reach', 'Stretch and recover', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-footwork-L02-003', 'tennis', 'tennis-footwork', 'Footwork', 2, 'Backpedal', 'Move back for lobs', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-footwork-L02-004', 'tennis', 'tennis-footwork', 'Footwork', 2, 'Ladder Drills', 'Quick feet patterns', 8, 35, false, 'complete_any_in_category_level_1'),
('tennis-footwork-L03-001', 'tennis', 'tennis-footwork', 'Footwork', 3, 'Drop Step', 'React to deep balls', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-footwork-L03-002', 'tennis', 'tennis-footwork', 'Footwork', 3, 'Adjustment Steps', 'Fine-tune positioning', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-footwork-L03-003', 'tennis', 'tennis-footwork', 'Footwork', 3, 'Open vs Closed Stance', 'Choose right stance', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-footwork-L03-004', 'tennis', 'tennis-footwork', 'Footwork', 3, 'Court Coverage', 'Full court movement', 9, 40, false, 'complete_any_in_category_level_2'),
('tennis-footwork-L04-001', 'tennis', 'tennis-footwork', 'Footwork', 4, 'First Step Speed', 'Explosive starts', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-footwork-L04-002', 'tennis', 'tennis-footwork', 'Footwork', 4, 'Direction Changes', 'Multi-directional agility', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-footwork-L04-003', 'tennis', 'tennis-footwork', 'Footwork', 4, 'Emergency Defense', 'Scramble and recover', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-footwork-L04-004', 'tennis', 'tennis-footwork', 'Footwork', 4, 'Transition Footwork', 'Defense to offense', 10, 45, false, 'complete_any_in_category_level_3'),
('tennis-footwork-L05-001', 'tennis', 'tennis-footwork', 'Footwork', 5, 'Nadal Slide', 'Clay court sliding', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-footwork-L05-002', 'tennis', 'tennis-footwork', 'Footwork', 5, 'Match Endurance', 'Late match footwork', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-footwork-L05-003', 'tennis', 'tennis-footwork', 'Footwork', 5, 'Pro Movement Patterns', 'ATP/WTA footwork', 12, 50, false, 'complete_any_in_category_level_4'),
('tennis-footwork-L05-004', 'tennis', 'tennis-footwork', 'Footwork', 5, 'Complete Court Coverage', 'Total movement mastery', 12, 50, false, 'complete_any_in_category_level_4')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description;